export const BUGS_LOADING = 'BUGS_LOADING';
export const ADD_BUGS = 'ADD_BUGS';
export const BUGS_FAILED = 'BUGS_FAILED';

export const FISHES_LOADING = 'FISHES_LOADING';
export const ADD_FISHES = 'ADD_FISHES';
export const FISHES_FAILED = 'FISHES_FAILED';

export const SEACREATURES_LOADING = 'SEACREATURES_LOADING';
export const ADD_SEACREATURES = 'ADD_SEACREATURES';
export const SEACREATURES_FAILED = 'SEACREATURES_FAILED';

export const ARTS_LOADING = 'ARTS_LOADING';
export const ADD_ARTS = 'ADD_ARTS';
export const ARTS_FAILED = 'ARTS_FAILED';

export const FOSSILS_LOADING = 'FOSSILS_LOADING';
export const ADD_FOSSILS = 'ADD_FOSSILS';
export const FOSSILS_FAILED = 'FOSSILS_FAILED';

export const ADD_BUG_DONATION = 'ADD_BUG_DONATION';
export const DELETE_BUG_DONATION = 'DELETE_BUG_DONATION';

export const ADD_FISH_DONATION = 'ADD_FISH_DONATION';
export const DELETE_FISH_DONATION = 'DELETE_FISH_DONATION';