export const BUGS_LOADING = 'BUGS_LOADING';
export const ADD_BUGS = 'ADD_BUGS';
export const BUGS_FAILED = 'BUGS_FAILED';

export const FISHES_LOADING = 'FISHES_LOADING';
export const ADD_FISHES = 'ADD_FISHES';
export const FISHES_FAILED = 'FISHES_FAILED';

export const SEACREATURES_LOADING = 'SEACREATURES_LOADING';
export const ADD_SEACREATURES = 'ADD_SEACREATURES';
export const SEACREATURES_FAILED = 'SEACREATURES_FAILED';