export const BUGS = [
    {
        id: 1,
        name: "common butterfly",
        northavailability: "September to June",
        southavailability: "March to December",
        time: "4am to 7pm",
        location: "Flying",
        rarity: "Common",
        price: 160,
        flickprice: 240,
        catchphrase: "I caught a common butterfly! They often flutter by!",
        museumphrase: "The common butterfly would have you believe it is but a beautiful friend flitting prettily about the flowers. Bah, I say! They may seem innocent things with their pretty white wings, but they hide a dark side! The common butterfly caterpillar is called a cabbage worm, you see, and it's a most voracious pest. The ravenous beasts chew through cabbage, broccoli, kale and the like with a devastating gusto. And my feathers! Their green coloring is truly GROSS! A hoo-rrific hue, I say.",
        image: "https://acnhapi.com/v1/images/bugs/1",
        icon: "https://acnhapi.com/v1/icons/bugs/1"
    },
    {
        id: 2,
        name: "yellow butterfly",
        northavailability: "March to June and September to October",
        southavailability: "September to December and March to April",
        time: "4am to 7pm",
        location: "Flying",
        rarity: "Common",
        price: 160,
        flickprice: 240,
        catchphrase: "I caught a yellow butterfly! Shouldn't all BUTTERflies be yellow?",
        museumphrase: "Allow me to enlighten you... The yellow butterfly is named for its yellow wings. Need I say more? If I must, then allow me to note that the female yellow butterfly can lay up to 600 eggs at a time! Bleech! And their creepy crawly caterpillars just love to chomp on clover plants. A recipe for disaster, I say. Just imagine reaching for a four-leaf clover, only to touch a larva instead! Yuck! The worst of luck!",
        image: "https://acnhapi.com/v1/images/bugs/2",
        icon: "https://acnhapi.com/v1/icons/bugs/2"
    },
    {
        id: 3,
        name: "tiger butterfly",
        northavailability: "March to September",
        southavailability: "September to March",
        time: "4am to 7pm",
        location: "Flying",
        rarity: "Common",
        price: 240,
        flickprice: 360,
        catchphrase: "I caught a tiger butterfly! I've earned my stripes!",
        museumphrase: "Tiger butterflies are known for their majestic wings, which many consider quite beautiful. Truth be told, I find them monstrous! Those strange striped patterns... They give this owl the goose bumps! And while you may imagine young tiger butterfly larvae to look like lovely green caterpillars...it's not so! Why, when tiger butterflies are but babes, they're covered in unsightly white, brown, and black spots. In this way, they camouflage themselves as...as...bird droppings! Putrid pests, indeed!",
        image: "https://acnhapi.com/v1/images/bugs/3",
        icon: "https://acnhapi.com/v1/icons/bugs/3"
    },
    {
        id: 4,
        name: "peacock butterfly",
        northavailability: "March to June",
        southavailability: "September to December",
        time: "4am to 7pm",
        location: "Flying near hybrid flowers",
        rarity: "Uncommon",
        price: 2500,
        flickprice: 3750,
        catchphrase: "I caught a peacock butterfly! Now it's my turn to strut my stuff!",
        museumphrase: "Pretty as a peacock? Bah, I say! The wings of the peacock butterfly may have a pattern similar to that of the beautiful bird... But its forewings are also often covered in a dark, velvety hair! You heard right! HAIRY wings! A hair-raising revelation indeed!",
        image: "https://acnhapi.com/v1/images/bugs/4",
        icon: "https://acnhapi.com/v1/icons/bugs/4"
    },
    {
        id: 5,
        name: "common bluebottle",
        northavailability: "April to August",
        southavailability: "September to February",
        time: "4am to 7pm",
        location: "Flying",
        rarity: "Common",
        price: 300,
        flickprice: 450,
        catchphrase: "I caught a common bluebottle! I'll put it in a rare green jar!",
        museumphrase: "The common bluebottle is a type of swallowtail butterfly with a bright blue line running down its wings. They fly quite nimbly, it seems, and are thus quite difficult to catch. But seeing how they've been known to slurp nutrients from MUD puddles... I simply CAN'T imagine wanting to catch one myself. What awful breath!",
        image: "https://acnhapi.com/v1/images/bugs/5",
        icon: "https://acnhapi.com/v1/icons/bugs/5"
    },
    {
        id: 6,
        name: "paper kite butterfly",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "8am to 7pm",
        location: "Flying",
        rarity: "Common",
        price: 1000,
        flickprice: 1500,
        catchphrase: "I caught a paper kite butterfly! Do I read it, fly it, or spreadit on toast?",
        museumphrase: "With its black-and-white-striped wing pattern, the paper kite butterfly is both elegant and pretty... PRETTY POISONOUS I MEAN! Hoo dear! Where was I? Oh yes... Even this butterfly's black-and-white-striped larva and little golden pupae are toxic to predators. Indeed, the paper kite butterfly's foul flavor is famous, and thus birds, in particular, steer clear of the fiends. THIS bird most of all!",
        image: "https://acnhapi.com/v1/images/bugs/6",
        icon: "https://acnhapi.com/v1/icons/bugs/6"
    },
    {
        id: 7,
        name: "great purple emperor",
        northavailability: "May to August",
        southavailability: "November to February",
        time: "4am to 7pm",
        location: "Flying",
        rarity: "Rare",
        price: 3000,
        flickprice: 4500,
        catchphrase: "I caught a great purple emperor! Its purple reign is over now!",
        museumphrase: "The great purple emperor lives high in the treetops and is renowned for its pretty purple-hued wings. Its impressive bird-like wingspan and elusive nature have made it a favorite among butterfly aficionados. But truth be told, the so-called great purple emperor has some not-so-great personal peculiarities. For one...it has two horrid HORNS upon its head when it is in its caterpillar form. For two...it has been known to dine on feces and animal carcasses! Hoo! That's why I call it the Emperor of EWWW!",
        image: "https://acnhapi.com/v1/images/bugs/7",
        icon: "https://acnhapi.com/v1/icons/bugs/7"
    },
    {
        id: 8,
        name: "monarch butterfly",
        northavailability: "September to November",
        southavailability: "March to May",
        time: "4am to 5pm",
        location: "Flying",
        rarity: "Common",
        price: 140,
        flickprice: 210,
        catchphrase: "I caught a monarch butterfly! Guess the butterflies are a democracy now!",
        museumphrase: "Did you know the monarch butterfly migrates south for the winter and returns north for the summer? Indeed, these horrid orange beasties do not tolerate the cold and travel 3,000 miles to escape the winter. During the journey, they cluster together in trees by the thousands just to stay warm. Imagine! Hordes of the foul flittering fiends huddled together in one place! If only they'd put on tiny coats instead.",
        image: "https://acnhapi.com/v1/images/bugs/8",
        icon: "https://acnhapi.com/v1/icons/bugs/8"
    },
    {
        id: 9,
        name: "emperor butterfly",
        northavailability: "June to September and December to March",
        southavailability: "June to September and December to March",
        time: "5pm to 8am",
        location: "Flying",
        rarity: "Uncommon",
        price: 4000,
        flickprice: 6000,
        catchphrase: "I caught an emperor butterfly! It's not your average monarch!",
        museumphrase: "The emperor butterfly is called the jewel of the forest. But its vivid blue hue... Ewww, let me tell you! The color does not come from a dye, but rather from light reflecting off layers of translucent scales. Yes, butterfly wings are covered in tiny scales! SCALES! Butterfly? Bah! More like snake of the sky!",
        image: "https://acnhapi.com/v1/images/bugs/9",
        icon: "https://acnhapi.com/v1/icons/bugs/9"
    },
    {
        id: 10,
        name: "agrias butterfly",
        northavailability: "April to September",
        southavailability: "October to March",
        time: "8am to 5pm",
        location: "Flying",
        rarity: "Uncommon",
        price: 3000,
        flickprice: 4500,
        catchphrase: "I caught an agrias butterfly! I wonder if it finds me disagrias-able?",
        museumphrase: "Some say the agrias butterfly is one of the most beautiful butterflies in the world. Bah, I say! BAH! They may have brightly colored wings, but the way they flutter and flitter...SO FOUL! In fact, the agrias butterfly flies so fast, it is quite a feat to catch one. I suppose I should congratulate you on your good fortune... But catching any bug seems a misfortune to me.",
        image: "https://acnhapi.com/v1/images/bugs/10",
        icon: "https://acnhapi.com/v1/icons/bugs/10"
    },
    {
        id: 11,
        name: "rajah brooke's birdwing",
        northavailability: "April to September and December to February",
        southavailability: "June to August and October to March",
        time: "8am to 5pm",
        location: "Flying",
        rarity: "Uncommon",
        price: 2500,
        flickprice: 3750,
        catchphrase: "I caught a Rajah Brooke's birdwing! Nothing else I'd rajah be doing!",
        museumphrase: "Did you know that the repulsive Rajah Brooke's birdwing loves to luxuriate in hot-springs water? It's true! Hoo! The males gather in groups to sip the moisture while the females hide in jungle trees. And though they dress to impress in red and green, these fluttering fiends are not just stylish... They're also quite malicious! Their little larvae pack a poisonous punch that's supposed to protect them from predators... But I suspect more diabolical designs.",
        image: "https://acnhapi.com/v1/images/bugs/11",
        icon: "https://acnhapi.com/v1/icons/bugs/11"
    },
    {
        id: 12,
        name: "queen alexandra's birdwing",
        northavailability: "May to September",
        southavailability: "November to March",
        time: "8am to 4pm",
        location: "Flying",
        rarity: "Rare",
        price: 4000,
        flickprice: 6000,
        catchphrase: "I caught a Queen Alexandra's birdwing! That's a feather in my cap!",
        museumphrase: "Hoo! The horror! This behemoth butterfly may be called a Queen Alexandra's birdwing... But I call it the Queen of My Nightmares! It is huge! Indeed, the world's hugest. No butterfly can best its foot-long wingspan. The larvae alone grow to more than 4 inches. As if that weren't appalling enough...they're poisonous! Murderous monsters, indeed!",
        image: "https://acnhapi.com/v1/images/bugs/12",
        icon: "https://acnhapi.com/v1/icons/bugs/12"
    },
    {
        id: 13,
        name: "moth",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "7pm to 4am",
        location: "Flying by light",
        rarity: "Common",
        price: 130,
        flickprice: 195,
        catchphrase: "I caught a moth! And I had a ball doing it!",
        museumphrase: "Many think the moth is strictly a nocturnal creature. Alas, no! These frightful fluttering beasts have been known to haunt the daylight and twilight hours too. Thus, there is no time of day one might escape the moth trait I dislike most of all—those feathery antennae! The mere thought of them gives my feathers goosebumps. And I'm no goose.",
        image: "https://acnhapi.com/v1/images/bugs/13",
        icon: "https://acnhapi.com/v1/icons/bugs/13"
    },
    {
        id: 14,
        name: "atlas moth",
        northavailability: "April to September",
        southavailability: "October to March",
        time: "7pm to 4am",
        location: "On trees",
        rarity: "Uncommon",
        price: 3000,
        flickprice: 4500,
        catchphrase: "I caught an Atlas moth! I bet it never gets lost!",
        museumphrase: "The Atlas moth is a monstrous thing! Not only is it one of the largest moths in the world... The tips of its wings look rather like the heads of venomous snakes! Despite its largeness and loathsome looks, the adult Atlas moth lives only for a few days. It emerges from its cocoon without a mouth, you see...and so cannot eat. I feel for the poor thing...but it is still foul!",
        image: "https://acnhapi.com/v1/images/bugs/14",
        icon: "https://acnhapi.com/v1/icons/bugs/14"
    },
    {
        id: 15,
        name: "madagascan sunset moth",
        northavailability: "April to September",
        southavailability: "October to March",
        time: "8am to 4pm",
        location: "Flying",
        rarity: "Uncommon",
        price: 2500,
        flickprice: 3750,
        catchphrase: "I caught a Madagascan sunset moth! Wow, you're not from around here!",
        museumphrase: "The Madagascan sunset moth is said to be the most beautiful moth in the world...a sentiment even I can't deny. While most moths are nocturnal, this one flutters about during the day, making good use of the light. That is, when the daylight reflects off its wings, a kaleidoscope of colors are revealed! Oh! Eh...too bad it has such startling red feet as a caterpillar. I might have found it almost tolerable otherwise. Almost, but not quite.",
        image: "https://acnhapi.com/v1/images/bugs/15",
        icon: "https://acnhapi.com/v1/icons/bugs/15"
    },
    {
        id: 16,
        name: "long locust",
        northavailability: "April to November",
        southavailability: "October to May",
        time: "8am to 7pm",
        location: "On the ground",
        rarity: "Common",
        price: 200,
        flickprice: 300,
        catchphrase: "I caught a long locust! Or, as I call it, a looooocust.",
        museumphrase: "As if the average locust weren't large enough...we must suffer the long locust too! The wretched beasts are known for their unusually long hind legs as well as their elongated heads. But that is hardly the long locusts' worst trait... I tell you, they spit brown goo when they're scared!",
        image: "https://acnhapi.com/v1/images/bugs/16",
        icon: "https://acnhapi.com/v1/icons/bugs/16"
    },
    {
        id: 17,
        name: "migratory locust",
        northavailability: "August to November",
        southavailability: "February to May",
        time: "8am to 7pm",
        location: "On the ground",
        rarity: "Uncommon",
        price: 600,
        flickprice: 900,
        catchphrase: "I caught a migratory locust! Things just went south for this guy!",
        museumphrase: "Ah yes, the lone migratory locust. It seems like such a harmless hopper as it bounces about in the grass. But beware! When these pests band together and travel in swarms, they leave devastation in their wake! Migratory locusts have gathered by the millions throughout history, wiping out crops and causing famine. That's why I always say, Never let a locust hang out with its friends!. That is precisely how a plague begins.",
        image: "https://acnhapi.com/v1/images/bugs/17",
        icon: "https://acnhapi.com/v1/icons/bugs/17"
    },
    {
        id: 18,
        name: "rice grasshopper",
        northavailability: "August to November",
        southavailability: "February to May",
        time: "8am to 7pm",
        location: "On the ground",
        rarity: "Common",
        price: 400,
        flickprice: 600,
        catchphrase: "I caught a rice grasshopper! I've been looking for agluten-free alternative...",
        museumphrase: "In point of fact, rice grasshoppers are an awful pest! They devour rice plants and wipe out the crucial crop. But revenge is sweet! These bugs are edible, you see, and so some folks eat them as way to get rid of them. When boiled in soy sauce, rice grasshoppers are quite tasty, it's said. Though why anyone would put an insect in their mouth is beyond me. The mere thought gives me the gags!",
        image: "https://acnhapi.com/v1/images/bugs/18",
        icon: "https://acnhapi.com/v1/icons/bugs/18"
    },
    {
        id: 19,
        name: "grasshopper",
        northavailability: "July to September",
        southavailability: "January to March",
        time: "8am to 5pm",
        location: "On the ground",
        rarity: "Common",
        price: 160,
        flickprice: 240,
        catchphrase: "I caught a grasshopper! They're a grass act!",
        museumphrase: "Grasshoppers are known for making a \"chirping\" sound. Though it doesn't sound like chirping to me... They make this rude racket by rubbing their hind legs against their wings. And though they eat seeds and pollen, they sometimes prey on smaller insects too. I say! Such violent table manners should not be tolerated! Horrible hoppers.",
        image: "https://acnhapi.com/v1/images/bugs/19",
        icon: "https://acnhapi.com/v1/icons/bugs/19"
    },
    {
        id: 20,
        name: "cricket",
        northavailability: "September to November",
        southavailability: "March to May",
        time: "5pm to 8am",
        location: "On the ground",
        rarity: "Common",
        price: 130,
        flickprice: 195,
        catchphrase: "I caught a cricket! What a chirp thrill!",
        museumphrase: "I say, where shall I start with the cricket? Well, to begin with, they are mostly nocturnal creatures. And for that you day-loving diurnal types should be grateful! Hoo! It means you don't have to lay eyes upon their prickly legs or overly long antennae like us night owls! Of course, crickets are best known for the chirping sound they make by rubbing their wings together. Some find the noise lovely to listen to. Alas, it only serves to remind me of another unpleasant fact... Which is to say...you will find a cricket's ears right next to its knees! I've gone weak in the knees at the mention of it!",
        image: "https://acnhapi.com/v1/images/bugs/20",
        icon: "https://acnhapi.com/v1/icons/bugs/20"
    },
    {
        id: 21,
        name: "bell cricket",
        northavailability: "September to October",
        southavailability: "March to April",
        time: "5pm to 8am",
        location: "On the ground",
        rarity: "Common",
        price: 430,
        flickprice: 645,
        catchphrase: "I found a bell cricket! It would make a great bellhop!",
        museumphrase: "The call of the bell cricket heralds the arrival of autumn. And I concede it is a rather pleasant sound. What I do NOT find pleasant is the way these things rub their strange wings together to make their song! Ick and blech! And to make matters worse, bell crickets have been known to shed two of their four wings! And they simply leave these wings where they fall, as if it were litter! I simply cannot abide such odious behavior.",
        image: "https://acnhapi.com/v1/images/bugs/21",
        icon: "https://acnhapi.com/v1/icons/bugs/21"
    },
    {
        id: 22,
        name: "mantis",
        northavailability: "March to November",
        southavailability: "September to May",
        time: "8am to 5pm",
        location: "On flowers",
        rarity: "Common",
        price: 430,
        flickprice: 645,
        catchphrase: "I caught a mantis! Man, 'tis so cool!",
        museumphrase: "Hoo! Don't let the mantis's angelic pose fool you...for it is truly monstrous. The mantis is known for its large size and tremendous strength...and for sickle-like arms that pack a punch. And though they tend to eat bugs and spiders...mantises have been known to dine on small animals too! And those eerie eyes! Oh my! Did you know it has five of them! Two big ones and three small! I shall faint if I think on it further...",
        image: "https://acnhapi.com/v1/images/bugs/22",
        icon: "https://acnhapi.com/v1/icons/bugs/22"
    },
    {
        id: 23,
        name: "orchid mantis",
        northavailability: "March to November",
        southavailability: "September to May",
        time: "8am to 5pm",
        location: "On white flowers",
        rarity: "Uncommon",
        price: 2400,
        flickprice: 3600,
        catchphrase: "I caught an orchid mantis! Our friendship is blooming!",
        museumphrase: "The orchid mantis is a bug whose brilliant colors and petal-shaped limbs give it the look of a flower. This masterful mimicry allows it to hide from predators in among the orchids. But oh this fraudulent flower! It lures other insects in to drink its nectar... And makes a meal of them instead! Imagine! To behold a beautiful bud... only to discover it's a bug instead! A repulsive revelation indeed!",
        image: "https://acnhapi.com/v1/images/bugs/23",
        icon: "https://acnhapi.com/v1/icons/bugs/23"
    },
    {
        id: 24,
        name: "honeybee",
        northavailability: "March to July",
        southavailability: "September to January",
        time: "8am to 5pm",
        location: "Flying",
        rarity: "Common",
        price: 200,
        flickprice: 300,
        catchphrase: "I caught a honeybee! Ah, sweet success!",
        museumphrase: "Did you know it takes a team of honeybees working together to transform flower nectar into honey? Indeed, forager bees suck nectar from flowers into their \"honey stomachs\" and then fly it to the hive. Hive bees then chew the substance and spit it into the honeycomb, fluttering their wings to dry it out. Yes, you could say honey is a tasty tribute to the hard work of the humble honeybee. Oh! Oh my! You mustn't confuse my lengthy description for admiration! At the end of the day, honeybees are still insects, and thus still ghastly! A wee bit less ghastly than most, I admit.",
        image: "https://acnhapi.com/v1/images/bugs/24",
        icon: "https://acnhapi.com/v1/icons/bugs/24"
    },
    {
        id: 25,
        name: "wasp",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "Shaking trees",
        rarity: "Common",
        price: 2500,
        flickprice: 3750,
        catchphrase: "I caught a wasp! That's gotta sting...",
        museumphrase: "Hoo! Allow me to share a fact with you! Wasps are sometimes called \"meat bees\" because... They. Eat. MEAT! MEAT! Of almost any sort! Surely you've seen what a menace they make of themselves at picnics. 'Tis hardly the worst of it, wot wot! Aggressive predators with venomous stingers, wasps not only hunt and eat other insects... they paralyze their prey, then drag their victims home ALIVE, leaving them for their larva to feed upon. Suddenly a simple sting seems quite tolerable.",
        image: "https://acnhapi.com/v1/images/bugs/25",
        icon: "https://acnhapi.com/v1/icons/bugs/25"
    },
    {
        id: 26,
        name: "brown cicada",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "8am to 5pm",
        location: "On trees",
        rarity: "Common",
        price: 250,
        flickprice: 375,
        catchphrase: "I caught a brown cicada! Now it probably feels blue, cicada.",
        museumphrase: "Cicadas are obnoxious insects. And not just brown cicadas, mind you...but all cicadas! They flex ribbed membranes on their torso called tymbals to make a loud snapping sound. So rude! Hoo! Yes, it is only the males who make the noise. Sometimes at a volume that can produce pain at close range! Appallingly inconsiderate, I must say...",
        image: "https://acnhapi.com/v1/images/bugs/26",
        icon: "https://acnhapi.com/v1/icons/bugs/26"
    },
    {
        id: 27,
        name: "robust cicada",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "8am to 5pm",
        location: "On trees",
        rarity: "Common",
        price: 300,
        flickprice: 450,
        catchphrase: "I caught a robust cicada! It DOES seem pretty lively! Not so energetic in the rain, huh?",
        museumphrase: "The robust cicada got its name from the chirping sound it makes, which is said to be quite...well...robust. But \"robust\" hardly describes it. Abrasive! Bombastic! Cacophonous! That's more like it! Beside the horrid caterwauling, this bug is known for its long wings, short body, and green coloring. But looking at a robust cicada is just as unpleasant as listening to one. My eyes AND my ears are offended.",
        image: "https://acnhapi.com/v1/images/bugs/27",
        icon: "https://acnhapi.com/v1/icons/bugs/27"
    },
    {
        id: 28,
        name: "giant cicada",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "8am to 5pm",
        location: "On trees",
        rarity: "Uncommon",
        price: 500,
        flickprice: 750,
        catchphrase: "I caught a giant cicada! I guess it's PRETTY big... (Guess it doesn't feel like singing in the rain!)",
        museumphrase: "The giant cicada is rather aptly named. That is, it's a truly enormous bug. Ugh! These beasts spend most of their lives underground where they gorge on tree roots. But once they emerge, they make an awful racket. In fact, some say their song sounds like a shrieking siren. I would rather listen to nails on a chalkboard.",
        image: "https://acnhapi.com/v1/images/bugs/28",
        icon: "https://acnhapi.com/v1/icons/bugs/28"
    },
    {
        id: 29,
        name: "walker cicada",
        northavailability: "August to September",
        southavailability: "February to March",
        time: "8am to 5pm",
        location: "On trees",
        rarity: "Common",
        price: 400,
        flickprice: 400,
        catchphrase: "I caught a walker cicada! Pffft... I walk all the time and no one calls me Walker ...(It must hate getting its feet wet.)",
        museumphrase: "The walker cicada is quite the noisy thing. I tell you, this impolite pest simply canNOT abide the quiet. In the heat of summer, the male strikes up a strange rattling song, hoping to woo a mate. When other male cicadas hear this rhythmic racket, they join right in... As if it were a sing-along! My head aches at the thought of it.",
        image: "https://acnhapi.com/v1/images/bugs/29",
        icon: "https://acnhapi.com/v1/icons/bugs/29"
    },
    {
        id: 30,
        name: "evening cicada",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "4am to 8am and 4pm and 7pm",
        location: "On trees",
        rarity: "Common",
        price: 550,
        flickprice: 825,
        catchphrase: "I caught an evening cicada! Better than an odding cicada...(This time it's WETTER than an odding cicada.)",
        museumphrase: "The evening cicada certainly knows how to ruin a quiet moment. As the sun sets, it strikes up a sad song so sonorous, one can't hear one's own thoughts! I'd feel sorry for its melancholy moods if it weren't so very vocal about how it feels. Ugh, please pipe down...",
        image: "https://acnhapi.com/v1/images/bugs/30",
        icon: "https://acnhapi.com/v1/icons/bugs/30"
    },
    {
        id: 31,
        name: "cicada shell",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "All day",
        location: "On trees",
        rarity: "Rare",
        price: 10,
        flickprice: 15,
        catchphrase: "I found a cicada shell! I'm glad the little guy came out of it!",
        museumphrase: "Cicadas! The nerve! Not only are they loud, they leave their cicada shells lying about! When it's time for a cicada nymph to turn into an adult, you see, it clings to a tree and sheds its exoskeleton. Then it just leaves this shell of its former self hanging right there! Awful manners, really...and awfully terrifying too.",
        image: "https://acnhapi.com/v1/images/bugs/31",
        icon: "https://acnhapi.com/v1/icons/bugs/31"
    },
    {
        id: 32,
        name: "red dragonfly",
        northavailability: "September to October",
        southavailability: "March to April",
        time: "8am to 7pm",
        location: "Flying",
        rarity: "Common",
        price: 180,
        flickprice: 270,
        catchphrase: "I caught a red dragonfly! Didn't even have to roll for initiative!",
        museumphrase: "I won't deny that the wretched red dragonfly is an elegant aeronaut. It manipulates its four wings quite uniquely so it can hover and maneuver through the air with ease. But the veins on its wings! What ghastly things! One can't help but gasp at the sight of them... Appalling aerodynamics, indeed!",
        image: "https://acnhapi.com/v1/images/bugs/32",
        icon: "https://acnhapi.com/v1/icons/bugs/32"
    },
    {
        id: 33,
        name: "darner dragonfly",
        northavailability: "April to October",
        southavailability: "October to April",
        time: "8am to 5pm",
        location: "Flying",
        rarity: "Common",
        price: 230,
        flickprice: 345,
        catchphrase: "I caught a darner dragonfly! It better watch its mouth!",
        museumphrase: "The darner dragonfly is the fastest dragonfly there is, flying at speeds up to 40 miles per hour! They all have a distinctive green hue, but the males have blue underbellies while females have yellow ones. It all sounds pleasant enough, no? Well, did you know their young eat tadpoles...and even some small fish! Worse, these creepy carnivores will eat each other in a pinch! Grotesque does not describe it...",
        image: "https://acnhapi.com/v1/images/bugs/33",
        icon: "https://acnhapi.com/v1/icons/bugs/33"
    },
    {
        id: 34,
        name: "banded dragonfly",
        northavailability: "May to October",
        southavailability: "November to April",
        time: "8am to 5pm",
        location: "Flying",
        rarity: "Rare",
        price: 4500,
        flickprice: 6750,
        catchphrase: "I did it! Did you see that? I caught a banded dragonfly!",
        museumphrase: "The banded dragonfly is known for its black-and-yellow-striped body, as well as for its piercing green eyes. And it is those very eyes that help make dragonflies master hunters, you see. Alas, when one looks at me, I can't help but feel it is sizing me up for a meal! Hoot! The horrors! Look away, fiend!",
        image: "https://acnhapi.com/v1/images/bugs/34",
        icon: "https://acnhapi.com/v1/icons/bugs/34"
    },
    {
        id: 35,
        name: "damselfy",
        northavailability: "November to February",
        southavailability: "May to August",
        time: "All day",
        location: "Flying",
        rarity: "Common",
        price: 500,
        flickprice: 750,
        catchphrase: "I caught a damselfly! Now it's a damselfly in distress!",
        museumphrase: "The colorful damselfly is similar to its cousin, the dragonfly, though it tends to be smaller and thinner. But don't let the delicate looks fool you! Much like the dragonfly, the damselfly is a ruthless predator. It loves to catch flies midair and eat them, and has been known to snack on spiders it plucks from the web! In short, it is not a dinner guest I would recommend... And it is not a menu I could keep down.",
        image: "https://acnhapi.com/v1/images/bugs/35",
        icon: "https://acnhapi.com/v1/icons/bugs/35"
    },
    {
        id: 36,
        name: "firefly",
        northavailability: "June",
        southavailability: "December",
        time: "7pm to 4am",
        location: "Flying (near water)",
        rarity: "Common",
        price: 300,
        flickprice: 450,
        catchphrase: "I caught a firefly! I'm on fire now!",
        museumphrase: "The firefly isn't a fly at all! It is a beetle, you see—and one known for its ghastly glowing backside. This light is called \"bioluminescence\" and it is caused by...by...a chemical reaction in the rump. Males flash about in the night sky to attract females, while their larvae turn on the glow to put off predators. Speaking of their yucky young, firefly larvae love to dine on snails! Hoo! Ewwww!",
        image: "https://acnhapi.com/v1/images/bugs/36",
        icon: "https://acnhapi.com/v1/icons/bugs/36"
    },
    {
        id: 37,
        name: "mole cricket",
        northavailability: "November to May",
        southavailability: "May to November",
        time: "All day",
        location: "Underground",
        rarity: "Common",
        price: 500,
        flickprice: 750,
        catchphrase: "I caught a mole cricket! I really dug it!",
        museumphrase: "Be warned, there is nowhere one might hide from the mole cricket. This plump pest has powerful front claws made for digging holes, and oh how it loves to burrow underground! A cousin to the grasshopper, it also has wings and can easily take to the air. And I swear this on my pinfeathers... Some have even been seen walking on water! Oh mercy, I may need a moment. This is making me feel rather woozy...",
        image: "https://acnhapi.com/v1/images/bugs/37",
        icon: "https://acnhapi.com/v1/icons/bugs/37"
    },
    {
        id: 38,
        name: "pondskater",
        northavailability: "May to September",
        southavailability: "November to March",
        time: "8am to 7pm",
        location: "On ponds and rivers",
        rarity: "Common",
        price: 130,
        flickprice: 195,
        catchphrase: "I caught a pondskater! Wonder if it can do a pond ollie...",
        museumphrase: "Putrid pondskaters! They walk on water, you know...which is most preposterous! It is a trick they perform by secreting oil onto the hairs of their feet. To which I say BLEEECH! And one must wonder... What will they do next? Walk on air? Walk through walls? Perish the thought...",
        image: "https://acnhapi.com/v1/images/bugs/38",
        icon: "https://acnhapi.com/v1/icons/bugs/38"
    },
    {
        id: 39,
        name: "diving beetle",
        northavailability: "May to September",
        southavailability: "November to March",
        time: "8am to 7pm",
        location: "On ponds and rivers",
        rarity: "Common",
        price: 800,
        flickprice: 1200,
        catchphrase: "I caught a diving beetle! Now I'm making a splash!",
        museumphrase: "Ah, the dastardly diving beetle! Famous for its distinctive round shape...and its voracious appetite. This powerful predator uses thick back legs covered in hairs to paddle after its prey. And it uses suction cups on its front legs to grip its quarry for good. My own legs have gone weak thinking about it...",
        image: "https://acnhapi.com/v1/images/bugs/39",
        icon: "https://acnhapi.com/v1/icons/bugs/39"
    },
    {
        id: 40,
        name: "giant water bug",
        northavailability: "April to September",
        southavailability: "October to March",
        time: "7pm to 8am",
        location: "On ponds and rivers",
        rarity: "Rare",
        price: 2000,
        flickprice: 3000,
        catchphrase: "I caught a giant water bug! It should've stayed in the water!",
        museumphrase: "How to put this gently? Ah yes... BEWARE the giant water bug! I tell you, this vicious predator has been known to attack fish, frogs, and even snakes! SNAKES! Truth be told, no one is safe! Its nickname is \"the toe-biter,\" for goodness sakes! Now, one final fact before I faint... The gruesome bug uses its nose...to inject its prey...with digestive juices. Hoo... Must stop thinking about...the unthinkable.",
        image: "https://acnhapi.com/v1/images/bugs/40",
        icon: "https://acnhapi.com/v1/icons/bugs/40"
    },
    {
        id: 41,
        name: "stinkbug",
        northavailability: "March to October",
        southavailability: "September to April",
        time: "All day",
        location: "On flowers",
        rarity: "Common",
        price: 120,
        flickprice: 180,
        catchphrase: "I caught a stinkbug! It lives up to its name!",
        museumphrase: "I daresay the name says it all... Stinkbugs are known for their stench. Hoo! Peeyew! As it happens, these crop-eating pests use straw-like mouths to pierce plants and drink the juices. And when threatened, they use a smelly chemical in their belly to release their odious odor! Hoo! How DO they live with themselves?",
        image: "https://acnhapi.com/v1/images/bugs/41",
        icon: "https://acnhapi.com/v1/icons/bugs/41"
    },
    {
        id: 42,
        name: "man-faced stink bug",
        northavailability: "March to October",
        southavailability: "September to April",
        time: "7pm to 8am",
        location: "On flowers",
        rarity: "Uncommon",
        price: 1000,
        flickprice: 1500,
        catchphrase: "I caught a man-faced stink bug! Reminds me of my uncle!",
        museumphrase: "Never mind this stink bug's smell. What you have here is a bug...with a FACE...on its BACK!! Wot-wot! Simply put, the man-faced stink bug has markings on its shell that resemble a human face. Once you notice this face, you cannot UN-notice it. Indeed, this face might haunt you forever. At least the face will distract you from the stink.",
        image: "https://acnhapi.com/v1/images/bugs/42",
        icon: "https://acnhapi.com/v1/icons/bugs/42"
    },
    {
        id: 43,
        name: "ladybug",
        northavailability: "March to June and October",
        southavailability: "September to December and April",
        time: "8am to 5pm",
        location: "On flowers",
        rarity: "Common",
        price: 200,
        flickprice: 300,
        catchphrase: "I caught a ladybug! Sorry to disturb you, ma'am.",
        museumphrase: "Yes. Yes. Ladybugs are quite beloved thanks to their tiny round shape and adorable spots. To that I say BAH! The fact of the matter is, some have stripes instead of spots. And SOME have no markings at all! No, I shall never understand why it is said that when a ladybug lands on you...you'll have good luck. I shall only have a fainting spell.",
        image: "https://acnhapi.com/v1/images/bugs/43",
        icon: "https://acnhapi.com/v1/icons/bugs/43"
    },
    {
        id: 44,
        name: "tiger beetle",
        northavailability: "February to November",
        southavailability: "August to April",
        time: "All day",
        location: "On the ground",
        rarity: "Uncommon",
        price: 1500,
        flickprice: 2250,
        catchphrase: "I caught a tiger beetle! I pounced first!",
        museumphrase: "The tiger beetle is extremely fleet of foot, though it runs in a rather peculiar way. That is, it sprints, then stops, then sprints again...using these speedy maneuvers to run down its prey. You see, the tiger beetle—like a real tiger—is a powerful predator. The mere thought of it giving chase gives me the willies. Tigers are terrifying at any size.",
        image: "https://acnhapi.com/v1/images/bugs/44",
        icon: "https://acnhapi.com/v1/icons/bugs/44"
    },
    {
        id: 45,
        name: "jewel beetle",
        northavailability: "April to August",
        southavailability: "November to February",
        time: "All day",
        location: "On tree stumps",
        rarity: "Uncommon",
        price: 2400,
        flickprice: 3600,
        catchphrase: "I caught a jewel beetle! It's a real gem!",
        museumphrase: "The green shimmer of the jewel beetle's wings is nothing short of nauseating...yes? No? Well, so says you. Though...jewel beetles were once prized by collectors who turned their iridescent wings into pretty jewelry. Why anyone would want to wear bug parts on their body is beyond me. Fashion foul indeed.",
        image: "https://acnhapi.com/v1/images/bugs/45",
        icon: "https://acnhapi.com/v1/icons/bugs/45"
    },
    {
        id: 46,
        name: "violin beetle",
        northavailability: "May to June and September to November",
        southavailability: "March to May and November to December",
        time: "All day",
        location: "On tree stumps",
        rarity: "Common",
        price: 450,
        flickprice: 675,
        catchphrase: "I caught a violin beetle! Apparently I'm as fit as a fiddle!",
        museumphrase: "The violin beetle gets its name from its shape. That is, SOME think it resembles the stringed instrument. If you ask me, this is an insult to violins! With its flat body and small head, the violin beetle looks like nothing but a repulsive bug, plain and simple. In fact it is so repulsive, it oozes a foul liquid when frightened! Ugh! This insect strikes a sour note indeed.",
        image: "https://acnhapi.com/v1/images/bugs/46",
        icon: "https://acnhapi.com/v1/icons/bugs/46"
    },
    {
        id: 47,
        name: "citrus long-horned beetle",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "On tree stumps",
        rarity: "Common",
        price: 350,
        flickprice: 525,
        catchphrase: "I caught a citrus long-horned beetle! Orange you happy for me?",
        museumphrase: "The citrus long-horned beetle is a putrid pest and a grave threat to trees. Hoo! It's true! Adults possess powerful jaws and use them to chomp through hard wood and plant fibers with ease. The little larvae are no better, boring bullet-like holes into innocent trees with gusto—citrus trees especially. Voracious and vile, indeed!",
        image: "https://acnhapi.com/v1/images/bugs/47",
        icon: "https://acnhapi.com/v1/icons/bugs/47"
    },
    {
        id: 48,
        name: "rosalia batesi beetle",
        northavailability: "May to September",
        southavailability: "November to March",
        time: "All day",
        location: "On tree stumps",
        rarity: "Uncommon",
        price: 3000,
        flickprice: 4500,
        catchphrase: "I caught a rosalia batesi beetle! That's easier to do than say!",
        museumphrase: "The rosalia batesi beetle is a type of longhorn beetle, so named for the long antenna upon its head. But did you know that longhorn beetles often grow antenna LONGER than their very own bodies, wot wot? As if this weren't odious enough, look closely and you will find these antenna...are covered in tufts of hair! Best not look closely, I say.",
        image: "https://acnhapi.com/v1/images/bugs/48",
        icon: "https://acnhapi.com/v1/icons/bugs/48"
    },
    {
        id: 49,
        name: "blue weevil beetle",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "All day",
        location: "On palm trees",
        rarity: "Common",
        price: 800,
        flickprice: 1200,
        catchphrase: "I caught a blue weevil beetle! It's the lesser of blue weevils!",
        museumphrase: "Yes, yes. The blue weevil beetle does come in beautiful shades of blue and green. The colors are so bright, some say it looks like a living jewel. But I say it looks like a weevil...and weevil rhymes with EVIL. Draw your own conclusions from there. Hoot! I certainly have!",
        image: "https://acnhapi.com/v1/images/bugs/49",
        icon: "https://acnhapi.com/v1/icons/bugs/49"
    },
    {
        id: 50,
        name: "dung beetle",
        northavailability: "December to February",
        southavailability: "June to August",
        time: "All day",
        location: "On the ground",
        rarity: "Common",
        price: 3000,
        flickprice: 4500,
        catchphrase: "I caught a dung beetle! This species likes feces!",
        museumphrase: "What can I say? The aptly-named dung beetle feeds on the feces of animals. Hoo! You heard right! This putrid pest rolls up balls of dung...and then rolls them away to dine on at a later date. As if that weren't atrocious enough, some dung beetles lay their eggs in the feces too! What a dreadful place to raise the young.",
        image: "https://acnhapi.com/v1/images/bugs/50",
        icon: "https://acnhapi.com/v1/icons/bugs/50"
    },
    {
        id: 51,
        name: "earth-boring dung beetle",
        northavailability: "July to September",
        southavailability: "January to March",
        time: "All day",
        location: "On the ground",
        rarity: "Common",
        price: 300,
        flickprice: 450,
        catchphrase: "I caught an earth-boring dung beetle! It's not boring at all!",
        museumphrase: "Earth-boring dung beetles are considered quite handsome by some, thanks to their metallic luster. In fact, some even think them to be good omens and bringers of favorable fortune. But I must protest! These field- ravaging pests love to burrow under piles of dung and lay their eggs. They raise their young under DUNG! Need I say more? Ick. I think not.",
        image: "https://acnhapi.com/v1/images/bugs/51",
        icon: "https://acnhapi.com/v1/icons/bugs/51"
    },
    {
        id: 52,
        name: "scarab beetle",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "11pm to 8am",
        location: "On trees",
        rarity: "Rare",
        price: 10000,
        flickprice: 15000,
        catchphrase: "I caught a scarab beetle! It's just a dung beetle with better hobbies.",
        museumphrase: "Collectors consider the scarab beetle quite the prize, thanks to its shiny metallic shell. But did you know this bug has no nose and uses its antenna to sense smells instead? In fact, the scarab beetle's plated antenna are quite unique and set it apart from other beetles. But ALL antennae are equally awful in my book.",
        image: "https://acnhapi.com/v1/images/bugs/52",
        icon: "https://acnhapi.com/v1/icons/bugs/52"
    },
    {
        id: 53,
        name: "drone beetle",
        northavailability: "June to August",
        southavailability: "December to February",
        time: "All day",
        location: "On trees",
        rarity: "Common",
        price: 200,
        flickprice: 300,
        catchphrase: "I caught a drone beetle! Shouldn't you have more propellers?",
        museumphrase: "I must say, the drone beetle is like that boorish acquaintance who is much too loud for polite company. That is, it is a large bug with a square head and is so named for the droning noise it makes when it flies. Furthermore, it has hooks on its feet that help it to cling tightly to trees. HOOK FEET... How gauche!",
        image: "https://acnhapi.com/v1/images/bugs/53",
        icon: "https://acnhapi.com/v1/icons/bugs/53"
    },
    {
        id: 54,
        name: "goliath beetle",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "5pm to 8am",
        location: "On palm trees",
        rarity: "Ultra-rare",
        price: 8000,
        flickprice: 12000,
        catchphrase: "I caught a goliath beetle! Am I a legend or what?",
        museumphrase: "Hoo! Ewww! The goliath beetle is a colossal creature that can grow up to four-inches long. Yes, they love to sup on sap and pollen, and frolic among the flowers. But did you know, the goliath beetle has a horn upon its head that it uses to fight its foes? And picture this... Each one of this behemoth's legs ends in pincers! Deep...calming...breaths...",
        image: "https://acnhapi.com/v1/images/bugs/54",
        icon: "https://acnhapi.com/v1/icons/bugs/54"
    },
    {
        id: 55,
        name: "saw stag",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "All day",
        location: "On trees",
        rarity: "Common",
        price: 2000,
        flickprice: 3000,
        catchphrase: "I caught a saw stag! Now I can't unsee it!",
        museumphrase: "The saw stag got its name from the shape of its pincers. That is, its pincers look like jagged saws! And I tell you, the bigger the beetle, the more saw-like teeth its giant jaws have. I say the saw stag seems more at home in a horror film than in nature. I have terrified myself just talking about it.",
        image: "https://acnhapi.com/v1/images/bugs/55",
        icon: "https://acnhapi.com/v1/icons/bugs/55"
    },
    {
        id: 56,
        name: "miyama stag",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "All day",
        location: "On trees",
        rarity: "Common",
        price: 1000,
        flickprice: 1500,
        catchphrase: "I caught a miyama stag! Its mandibles are jaw-dropping!",
        museumphrase: "The miyama stag has protrusions on its head that resemble ears... And yet, the ugly lumps are not ears! It is, however, called a \"stag\" beetle because of the large, deer-like horns upon its head. And the word \"miyama\" in its name means \"deep mountain\" in Japanese. Feel free to call it what you like. I will simply call it DISGUSTING. Disgusting stag beetle does have a ring.",
        image: "https://acnhapi.com/v1/images/bugs/56",
        icon: "https://acnhapi.com/v1/icons/bugs/56"
    },
    {
        id: 57,
        name: "giant stag",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "11pm to 8am",
        location: "On trees",
        rarity: "Rare",
        price: 10000,
        flickprice: 15000,
        catchphrase: "Whoaaa! I caught a giant stag! I'm gonna need way bigger pockets...",
        museumphrase: "It is said the giant stag is a popular pet among bug enthusiasts. Though how one might consider oneself enthusiastic about bugs is quite beyond me... But I digress. Giant stags look fearsome with their enormous curved mandibles. But in truth, they're really quite cowardly. Oh how they love to hide away in rotting wood, only to reveal themselves under the cover of dark. Hoot! I shall never turn off the lights again!",
        image: "https://acnhapi.com/v1/images/bugs/57",
        icon: "https://acnhapi.com/v1/icons/bugs/57"
    },
    {
        id: 58,
        name: "rainbow stag",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "7pm to 8am",
        location: "On trees",
        rarity: "Rare",
        price: 6000,
        flickprice: 9000,
        catchphrase: "I caught a rainbow stag! Its rainbow armor is so shiny!",
        museumphrase: "Rainbows are beautiful things, I'm sure we all agree. But rainbow stag beetles? Bleech! Yes, yes, this beetle's back and belly shine with a pretty rainbow- colored luster. But that does not change the fact this bug has large pincers on its face and loves to pick a fight! If one can wish upon a rainbow, then I wish to stay far away from the rainbow stag. Perhaps I've picked the wrong profession.",
        image: "https://acnhapi.com/v1/images/bugs/58",
        icon: "https://acnhapi.com/v1/icons/bugs/58"
    },
    {
        id: 59,
        name: "cyclommatus stag",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "5pm to 8am",
        location: "On palm trees",
        rarity: "Ultra-rare",
        price: 8000,
        flickprice: 12000,
        catchphrase: "I caught a cyclommatus stag! Those mandibles are a mouthful!",
        museumphrase: "The cyclommatus stag is known for its giant jaws, which can be even larger than its body. Its round eyes and silver color make it a beloved beetle. Though how one could love a beetle is beyond me. Imagine being pinched by those long jaws, and the pain it would cause! Ouch and ewww!",
        image: "https://acnhapi.com/v1/images/bugs/59",
        icon: "https://acnhapi.com/v1/icons/bugs/59"
    },
    {
        id: 60,
        name: "golden stag",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "5pm to 8am",
        location: "On palm trees",
        rarity: "Ultra-rare",
        price: 12000,
        flickprice: 18000,
        catchphrase: "Wooooow! I caught a golden stag! Does this mean I can retire?",
        museumphrase: "Yes. Yes. The golden stag beetle is quite the prize thanks to its metallic gold coloring. But let me speak plainly... The golden stag is NOT made of gold. It is made of BUG, through and through. And thus it is vile! Golden stag? Bah! Gross stag is more like it.",
        image: "https://acnhapi.com/v1/images/bugs/60",
        icon: "https://acnhapi.com/v1/icons/bugs/60"
    },
    {
        id: 61,
        name: "giraffe stag",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "5pm to 8am",
        location: "On palm trees",
        rarity: "Ultra-rare",
        price: 12000,
        flickprice: 18000,
        catchphrase: "I caught a giraffe stag! Does that make it a longhorn?",
        museumphrase: "The giraffe stag beetle is a bug of preposterous proportions. Not only is its body rather large, it has two long, jagged jaws that can put it over five inches in size! The giraffe stag beetle's long jaws have been compared to the long neck of the giraffe...hence the name. But I say such comparisons are a stretch. Giraffe necks are NOT lined with spikes! If I were a giraffe, I would protest.",
        image: "https://acnhapi.com/v1/images/bugs/61",
        icon: "https://acnhapi.com/v1/icons/bugs/61"
    },
    {
        id: 62,
        name: "horned dynastid",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "5pm to 8am",
        location: "On trees",
        rarity: "Common",
        price: 1350,
        flickprice: 2025,
        catchphrase: "I caught a horned dynastid! I'd hate to hear it honk that schnoz!",
        museumphrase: "The horned dynastid's head is shaped like a samurai warrior's helmet, hootie-hoo! It would be a most impressive fact if their large size wasn't so horrifying! Adult males use their huge horned heads for fighting and digging, while the females have no such need. As for their larvae and pupae, they too are quite large and feed on rotting wood at a tremendous pace. A foul feast, indeed!",
        image: "https://acnhapi.com/v1/images/bugs/62",
        icon: "https://acnhapi.com/v1/icons/bugs/62"
    },
    {
        id: 63,
        name: "horned atlas",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "5pm to 8am",
        location: "On palm trees",
        rarity: "Ultra-rare",
        price: 8000,
        flickprice: 12000,
        catchphrase: "I caught a horned atlas! I didn't even need a map!",
        museumphrase: "Beware the horned atlas! I tell you, this rhinoceros beetle is known for its violent temperament! The males use the three large horns on their heads to fight amongst each other for dominance. But it is their young that truly give me the cold sweats. You see, their larvae grow quite large and, worst of all...they bite! It is the stuff of nightmares, I say.",
        image: "https://acnhapi.com/v1/images/bugs/63",
        icon: "https://acnhapi.com/v1/icons/bugs/63"
    },
    {
        id: 64,
        name: "horned elephant",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "5pm to 8am",
        location: "On palm trees",
        rarity: "Ultra-rare",
        price: 8000,
        flickprice: 12000,
        catchphrase: "I caught a horned elephant! I think it's too small to ride...",
        museumphrase: "The horned elephant beetle certainly lives up to its namesake. Not only does the horn on its head resemble the trunk of an elephant... It is also one of the heaviest beetles in the world! Size aside, allow me to reveal the real reason I find horned elephant beetles so repugnant... Their backs are covered in a fine coat of hair! Hirsute beetles! Hoot! The horror!",
        image: "https://acnhapi.com/v1/images/bugs/64",
        icon: "https://acnhapi.com/v1/icons/bugs/64"
    },
    {
        id: 65,
        name: "horned hercules",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "5pm to 8am",
        location: "On palm trees",
        rarity: "Ultra-rare",
        price: 12000,
        flickprice: 18000,
        catchphrase: "I caught a horned hercules! Guess I was stronger!",
        museumphrase: "The horned hercules is not only known for its tremendous strength, but for its size as well. It can grow up to seven-inches long and has powerful pincers covered in hair that help with gripping! As if this weren't ghastly enough, these behemoth beetles let loose a foul odor that fends off enemies... And offends my sense of smell.",
        image: "https://acnhapi.com/v1/images/bugs/65",
        icon: "https://acnhapi.com/v1/icons/bugs/65"
    },
    {
        id: 66,
        name: "walking stick",
        northavailability: "July to November",
        southavailability: "January to May",
        time: "4am to 8am and 5pm to 7pm",
        location: "On trees",
        rarity: "Uncommon",
        price: 600,
        flickprice: 900,
        catchphrase: "I caught a walking stick! Check out its walking schtick! Look, these are the jokes, OK?",
        museumphrase: "The walking stick looks just like a twig, does it not? Hoo! It even has knots like a real twig would! These bashful bugs mimic plants in this way to hide from predators. A noble goal, you might say. But though the deceptive wretches fool some, they do not fool me! I see these bugs for what they are... Monsters, plain and simple! I say, did you know that walking sticks can grow to two feet long?! Imagine running into one! Surely I would faint.",
        image: "https://acnhapi.com/v1/images/bugs/66",
        icon: "https://acnhapi.com/v1/icons/bugs/66"
    },
    {
        id: 67,
        name: "walking leaf",
        northavailability: "July to September",
        southavailability: "January to March",
        time: "All day",
        location: "Under trees",
        rarity: "Uncommon",
        price: 600,
        flickprice: 900,
        catchphrase: "I caught a walking leaf! It seems to be taking it in stride!",
        museumphrase: "What a fraud! What a phony! The walking leaf is, in fact, the very embodiment of a lie! This master mimic looks like a tree leaf all the way down to the tiniest details. In fact, this bug has been known to sway to and fro as it walks...just so it looks like a leaf blown by the wind! And the fakery works! These insects look so much like leaves that even leaf-eating insects nibble on them! Lying liars, indeed!",
        image: "https://acnhapi.com/v1/images/bugs/67",
        icon: "https://acnhapi.com/v1/icons/bugs/67"
    },
    {
        id: 68,
        name: "bagworm",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "Shaking trees",
        rarity: "Common",
        price: 600,
        flickprice: 900,
        catchphrase: "I caught a bagworm! Guess I'm a bragworm!",
        museumphrase: "The bagworm is, in fact, not a worm at all, but a caterpillar instead. The filthy fraud uses silk and leaves to spin a cozy bag for it to hide inside—hence the name. Some find it cute the way bagworms dangle from trees. But the truth is they're gluttonous monsters. These beasts love to stuff their bug- gullets full of leaves, devouring the very trees they hang upon. Wretched villains is what they are.",
        image: "https://acnhapi.com/v1/images/bugs/68",
        icon: "https://acnhapi.com/v1/icons/bugs/68"
    },
    {
        id: 69,
        name: "ant",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "On rotten food",
        rarity: "Common",
        price: 900,
        flickprice: 1350,
        catchphrase: "I caught an ant! TELL ME WHERE THE QUEEN IS!",
        museumphrase: "I warn you, the ant may be a small bug, but it finds scary strength in numbers. You see, the ant itself is the strongest creature in the world in relation to its size. One of these diminutive fiends can carry 50 times its own bodyweight! And if it wants to lift something even larger... Why, it simply calls on its ant friends to join the effort. Creepy cooperation, I say...",
        image: "https://acnhapi.com/v1/images/bugs/69",
        icon: "https://acnhapi.com/v1/icons/bugs/69"
    },
    {
        id: 70,
        name: "hermit crab",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "7pm to 8am",
        location: "On the beach",
        rarity: "Common",
        price: 1000,
        flickprice: 1500,
        catchphrase: "I caught a hermit crab! I think it wanted to be left alone!",
        museumphrase: "The hermit crab is not an insect... Though it most certainly resembles one. Blech! It looks much like a spider—what with its creepy eyes and crawly legs—but is, in fact, a crustacean. As such, the hermit crab has 10 legs and also wears a shell. But it doesn't grow this shell itself. It slips its soft body into shells left behind by snails, you see, and moves into ever-larger ones as it grows. Talk about a strange way to make a home.",
        image: "https://acnhapi.com/v1/images/bugs/70",
        icon: "https://acnhapi.com/v1/icons/bugs/70"
    },
    {
        id: 71,
        name: "wharf roach",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "On beach rocks",
        rarity: "Common",
        price: 200,
        flickprice: 300,
        catchphrase: "I caught a wharf roach! This water-loving roach has no pier!",
        museumphrase: "The wharf roach is an omnivore, which is merely a polite way of saying it will eat almost anything. This skittering scavenger and its uncouth appetite help keep beaches clean, it's said. But I dare say, their long antenna and bulging eyes turn MY stomach. Unappetizing indeed...",
        image: "https://acnhapi.com/v1/images/bugs/71",
        icon: "https://acnhapi.com/v1/icons/bugs/71"
    },
    {
        id: 72,
        name: "fly",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "Near trash",
        rarity: "Common",
        price: 60,
        flickprice: 90,
        catchphrase: "I caught a fly! I was just wingin' it...",
        museumphrase: "The foul fly is quite the disquieting creature. I tell you, it tastes its food with its feet! Yeep! In fact, when flies rub their legs together, they do so to get rid of debris blocking their taste receptors. And did you know, their hairy toes release a sticky goo so they can walk on any surface? Even your ceiling! This gross goo gets on your food too!",
        image: "https://acnhapi.com/v1/images/bugs/72",
        icon: "https://acnhapi.com/v1/icons/bugs/72"
    },
    {
        id: 73,
        name: "mosquito",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "5pm to 4am",
        location: "Flying",
        rarity: "Common",
        price: 130,
        flickprice: 195,
        catchphrase: "I caught a mosquito! It's itching for a fight!",
        museumphrase: "As everyone knows, the mosquito is a vampiric pest that sucks blood from innocent bystanders. But did you know that only the females suck blood? Hoo! It's true! They need it to make their eggs. When they sink their snout into our skin, they inject us with a saliva that helps them slurp up their meal. It's that saliva that makes us itch and scratch, you know. Hoo! So rude!",
        image: "https://acnhapi.com/v1/images/bugs/73",
        icon: "https://acnhapi.com/v1/icons/bugs/73"
    },
    {
        id: 74,
        name: "flea",
        northavailability: "April to November",
        southavailability: "October to May",
        time: "All day",
        location: "On villagers",
        rarity: "Common",
        price: 70,
        flickprice: 105,
        catchphrase: "I caught a flea! The curse is lifted.",
        museumphrase: "Allow me to be blunt. The flea is foul! It is also disgusting, repugnant, and vile! Hoo! But I digress... This horrid pest sucks the blood of humans and animals. In fact, it is the flea's own saliva that makes us itch! And did you know their legs are so strong, they can jump more than 50 times their body length? So you see, it's all too easy for a flea to jump from you to me! I itch at the very thought.",
        image: "https://acnhapi.com/v1/images/bugs/74",
        icon: "https://acnhapi.com/v1/icons/bugs/74"
    },
    {
        id: 75,
        name: "snail",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "On rocks and bush (when raining)",
        rarity: "Common",
        price: 250,
        flickprice: 375,
        catchphrase: "I caught a snail! It's...not much to brag about.",
        museumphrase: "Snails are not insects, I'll admit. But they're just as revolting to me. Snails are mollusks, you see, and are born wearing shells they cannot remove. Instead, their shells get bigger and bigger as they grow. Hoo! They must get heavy, don't you know! I suppose that's why they need a trail of mucus to move about. A truly foul form of transportation.",
        image: "https://acnhapi.com/v1/images/bugs/75",
        icon: "https://acnhapi.com/v1/icons/bugs/75"
    },
    {
        id: 76,
        name: "pill bug",
        northavailability: "September to June",
        southavailability: "March to December",
        time: "11pm to 4pm",
        location: "Hitting rocks",
        rarity: "Common",
        price: 250,
        flickprice: 375,
        catchphrase: "I caught a pill bug! That's a tough act to swallow!",
        museumphrase: "Blech, the pill bug! Children delight at the way these beasts roll into balls when poked... But the appeal is utterly lost on me. One look at their leggy undersides... Hoo! Ewww! How they wriggle! Young pill bugs shed their exo- skeletons as they grow, and in doing so, sprout another pair of legs. As if 12 appendages weren't alarming enough! Yuck, I say. Yuck!",
        image: "https://acnhapi.com/v1/images/bugs/76",
        icon: "https://acnhapi.com/v1/icons/bugs/76"
    },
    {
        id: 77,
        name: "centipede",
        northavailability: "September to June",
        southavailability: "March to December",
        time: "4pm to 11pm",
        location: "Hitting rocks",
        rarity: "Common",
        price: 300,
        flickprice: 450,
        catchphrase: "I caught a centipede! 99 more and I'll have a dollarpede!",
        museumphrase: "The centipede's name means \"100 legs.\" But I tell you now, that's a lie! These ugly bugs can have as few as 15 pairs of legs...or as many as 171. But because of how their bodies are segmented, they never have exactly 100! Hoo! It's true! You know what else is true? Centipedes are carnivorous, aggressive, and venomous! And their bite is quite painful too! HOO-rrible things, I say.",
        image: "https://acnhapi.com/v1/images/bugs/77",
        icon: "https://acnhapi.com/v1/icons/bugs/77"
    },
    {
        id: 78,
        name: "spider",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "7pm to 8am",
        location: "Shaking trees",
        rarity: "Common",
        price: 480,
        flickprice: 720,
        catchphrase: "I caught a spider! I spied 'er first!",
        museumphrase: "The spider is renowned for having eight eyes and eight legs... WHICH IS SIX TOO MANY, I SAY! Oh dear. I do apologize. Now where was I? Most spiders are carnivorous. In fact, some will eat creatures several times larger than themselves. To catch their prey, many of these ruthless predators spin sticky webs of surprising strength. Worse yet, they've also been known to ambush their victims, and some even chase down their meals! All this talk about the feeding habits of spiders... I'm feeling quite queasy. Hoot! The horror!",
        image: "https://acnhapi.com/v1/images/bugs/78",
        icon: "https://acnhapi.com/v1/icons/bugs/78"
    },
    {
        id: 79,
        name: "tarantula",
        northavailability: "November to April",
        southavailability: "May to October",
        time: "7pm to 4am",
        location: "On the ground",
        rarity: "Common",
        price: 8000,
        flickprice: 12000,
        catchphrase: "I caught a tarantula! This situation just got hairy!",
        museumphrase: "As giant spiders go, the tarantula is said to be quite docile. But have you ever seen such foul fuzziness?! It is a fact, tarantulas have barbed belly hair! I say again...BARBED. BELLY. HAIR! These awful arachnids let loose their spiky, itchy hairs to protect themselves from predators. But seeing how tarantulas also prey on frogs, mice, and even birds, one must ask... Who needs protecting from whom?! Hoo! Who indeed!",
        image: "https://acnhapi.com/v1/images/bugs/79",
        icon: "https://acnhapi.com/v1/icons/bugs/79"
    },
    {
        id: 80,
        name: "scorpion",
        northavailability: "May to October",
        southavailability: "November to April",
        time: "7pm to 4am",
        location: "On the ground",
        rarity: "Common",
        price: 8000,
        flickprice: 12000,
        catchphrase: "I caught a scorpion! It was a sting operation!",
        museumphrase: "The scorpion...how should I put this? Those legs! Those pincers! That tail! And that venomous stinger! It's as if someone took all the most awful insect parts...and put them together to make the scorpion! All scorpions are venomous, you know! Though I understand that only a few kinds are truly deadly. I fear I might die just thinking about it.",
        image: "https://acnhapi.com/v1/images/bugs/80",
        icon: "https://acnhapi.com/v1/icons/bugs/80"
    }
];