export const FISHES = [
    {
        id: 1,
        name: "bitterling",
        northavailability: "November to March",
        southavailability: "May to September",
        time: "All day",
        location: "River",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 900,
        cjprice: 1350,
        catchphrase: "I caught a bitterling! It's mad at me, but only a little.",
        museumphrase: "Bitterlings hide their eggs inside large bivalves—like clams—where the young can stay safe until grown. The bitterling isn't being sneaky. No, their young help keep the bivalve healthy by eating invading parasites! It's a wonderful bit of evolutionary deal making, don't you think? Each one keeping the other safe... Though eating parasites does not sound like a happy childhood... Is that why the fish is so bitter?",
        image: "https://acnhapi.com/v1/images/fish/1",
        icon: "https://acnhapi.com/v1/icons/fish/1"
    },
    {
        id: 2,
        name: "pale chub",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "9am to 4pm",
        location: "River",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 200,
        cjprice: 300,
        catchphrase: "I caught a pale chub! That name seems a bit judgy...",
        museumphrase: "The pale chub is a river fish with simple back-and-silver coloring. Interestingly, the males' coloring becomes most vibrant when he's trying to attract a mate! Though normally plain, these fellows really know how to look stylish when they want to. Perhaps I could learn a thing or two from the pale chub...",
        image: "https://acnhapi.com/v1/images/fish/2",
        icon: "https://acnhapi.com/v1/icons/fish/2"
    }, {
        id: 3,
        name: "crucian carp",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "River",
        rarity: "Common",
        shadow: "Small (2)",
        price: 160,
        cjprice: 240,
        catchphrase: "I caught a crucian carp! My skills are sharp!",
        museumphrase: "I wonder... Do you know how to tell the difference between a crucian carp and a standard-issue carp? It's quite easy to tell the two apart... One must simply locate the barbels. Or, rather, the lack of them! And just what is a barbel, you ask? Well, a barbel looks a little something like a mustache. A run-of-the-mill carp will sport this unsightly \"facial hair,\" while a crucian carp is considerably better groomed! I tried to grow a mustache when I was younger. It never did fill in quite right... All for the best in the end, as mustaches go so much better with noses than with beaks!",
        image: "https://acnhapi.com/v1/images/fish/3",
        icon: "https://acnhapi.com/v1/icons/fish/3"
    }, {
        id: 4,
        name: "dace",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "4pm to 9am",
        location: "River",
        rarity: "Common",
        shadow: "Medium (3)",
        price: 240,
        cjprice: 360,
        catchphrase: "I caught a dace! Hope I have some space!",
        museumphrase: "Dace are shiny little fish that enjoy freshwater streams with gravelly bottoms and plenty of sunlight. What a fishy paradise...until the larger fish move in and begin eating the dace! Sadly, the shiny dace are easy for other fish to spot, which makes them a popular snack. However, this particular specimen here has no need to worry. There's a strict \"No Eating Your Neighbor\" policy at this institution.",
        image: "https://acnhapi.com/v1/images/fish/4",
        icon: "https://acnhapi.com/v1/icons/fish/4"
    }, {
        id: 5,
        name: "carp",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "Pond",
        rarity: "Common",
        shadow: "Medium (4)",
        price: 300,
        cjprice: 450,
        catchphrase: "I caught a carp! If I catch another they can carpool!",
        museumphrase: "Oh, the carp... have you ever seen their teeth? For your sake, I hope you have not! Carp have teeth in their throat strong enough to crunch on hard things like shells and fingers! A good rule of thumb when dealing with other species is to keep your fingers out of their mouths. Although, having neither thumbs nor fingers, I am quite safe from this little fellow!",
        image: "https://acnhapi.com/v1/images/fish/5",
        icon: "https://acnhapi.com/v1/icons/fish/5"
    }, {
        id: 6,
        name: "koi",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "4pm to 9am",
        location: "Pond",
        rarity: "Uncommon",
        shadow: "Medium (4)",
        price: 4000,
        cjprice: 6000,
        catchphrase: "I caught a koi! I don't know why it's so shy... or such a bad speller...",
        museumphrase: "Koi are a variety of carp bred for their color mutations...starting more than a thousand years ago! Well, one glance at their impressive coloring tells you that the centuries of effort were worth it. And even today people still selectively breed koi in search of new color combinations! One marvels at the thought of what the koi may look like in another thousand years.",
        image: "https://acnhapi.com/v1/images/fish/6",
        icon: "https://acnhapi.com/v1/icons/fish/6"
    }, {
        id: 7,
        name: "goldfish",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "Pond",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 1300,
        cjprice: 1950,
        catchphrase: "I caught a goldfish! It's worth its weight in fish!",
        museumphrase: "Goldfish are so cute and delicate... but do you know how big they can get? Why, they can grow up to... a foot in length! Well, sometimes. The size of the tank they're kept in tends to restrict their growth. And just how big will this goldfish get in our large museum tank? I look forward to finding out!",
        image: "https://acnhapi.com/v1/images/fish/7",
        icon: "https://acnhapi.com/v1/icons/fish/7"
    }, {
        id: 8,
        name: "pop-eyed goldfish",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "9am to 4pm",
        location: "Pond",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 1300,
        cjprice: 1950,
        catchphrase: "I got a pop-eyed goldfish! It looks so...surprised!",
        museumphrase: "Pop-eyed goldfish have, as the name suggests, huge round eyes. But as babies they look like other goldfish! As they grow, their eyes begin to pop out and they gain their, hoo, distinct appearance... Imagine the poor fish fancier who unknowingly bought one! Their eyes might well pop out just as far!",
        image: "https://acnhapi.com/v1/images/fish/8",
        icon: "https://acnhapi.com/v1/icons/fish/8"
    }, {
        id: 9,
        name: "ranchu goldfish",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "9am - 4pm",
        location: "Pond",
        rarity: "Uncommon",
        shadow: "Small (2)",
        price: 4500,
        cjprice: 6750,
        catchphrase: "I caught a ranchu goldfish! But I prefer balsamicu goldfish!",
        museumphrase: "The ranchu goldfish is a charming relative of the goldfish with a bumpy head and stout, round body. They have ordinary heads when born, but develop impressive rectangular heads after about three years. Supposedly their head shape changes depending on factors like the size of their tank... So ranchu goldfish enthusiasts aim to raise perfectly shaped specimens and work hard to achieve this. Of course, no one asks the ranchu goldfish themselves what shape they want their heads to be...",
        image: "https://acnhapi.com/v1/images/fish/9",
        icon: "https://acnhapi.com/v1/icons/fish/9"
    }, {
        id: 10,
        name: "killifish",
        northavailability: "April to August",
        southavailability: "October to February",
        time: "All day",
        location: "Pond",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 300,
        cjprice: 450,
        catchphrase: "I caught a killifish! The streams are safe again.",
        museumphrase: "Ah, the magnificent killifish! Did you know there are over 1,000 different species? My own favorite killifish species are the mangrove, which can live on land for weeks, breathing air! And the mummichog, the first fish ever brought to space. I wonder if the killifish you've brought me is related to either those intrepid explorers?",
        image: "https://acnhapi.com/v1/images/fish/10",
        icon: "https://acnhapi.com/v1/icons/fish/10"
    }, {
        id: 11,
        name: "crawfish",
        northavailability: "April to September",
        southavailability: "October to March",
        time: "All day",
        location: "Pond",
        rarity: "Common",
        shadow: "Small (2)",
        price: 200,
        cjprice: 300,
        catchphrase: "I caught a crawfish! Or else it's a lobster and I'm a giant!",
        museumphrase: "Ohoo! So you have found a crawfish. Neither crab nor lobster, crawfish evolved in an interesting manner. Beware their fearsome pinchy pinchers! Behold their many legs! I say! It is a big bug-like, eh wot...The more I look at it, the more unsettled I feel... Let's be done with this and never speak of it again, shall we?",
        image: "https://acnhapi.com/v1/images/fish/11",
        icon: "https://acnhapi.com/v1/icons/fish/11"
    },
    {
        id: 12,
        name: "soft-shelled turtle",
        northavailability: "August to September",
        southavailability: "February to March",
        time: "4pm to 9am",
        location: "River",
        rarity: "Uncommon",
        shadow: "Medium (4)",
        price: 3750,
        cjprice: 5625,
        catchphrase: "I caught a soft-shelled turtle! I can really shell it out! (I should take a shellfie!)",
        museumphrase: "These relatives of common turtles will not let go when they decide to bite down on something. Although they can be quite shy, they will become a bit aggressive when threatened. They are often found in water and are very good swimmers because of the flat shape of their shells. They swim with their snouts over the surface of the water so they can breathe. Soft-shelled turtles aren't safe to hold because they are so prone to biting at the slightest movement. However, if one bites down on you, it will usually let go when you put it safely back in the water.",
        image: "https://acnhapi.com/v1/images/fish/12",
        icon: "https://acnhapi.com/v1/icons/fish/12"
    },
    {
        id: 13,
        name: "snapping turtle",
        northavailability: "April to October",
        southavailability: "October to April",
        time: "9pm to 4am",
        location: "River",
        rarity: "Common",
        shadow: "Large (5)",
        price: 5000,
        cjprice: 7500,
        catchphrase: "I caught a snapping turtle! How can it snap without fingers?",
        museumphrase: "The snapping turtle is a large turtle known for it's crocodile-like body and long claws. No, wait-- it is better known for it's ferocious bite, which it can deliver with shocking speed for a turtle. NO, WAIT-- it is BEST known for that time one chased me across a parking lot and I had to climb on top of a car.",
        image: "https://acnhapi.com/v1/images/fish/13",
        icon: "https://acnhapi.com/v1/icons/fish/13"
    }, {
        id: 14,
        name: "tadpole",
        northavailability: "March to July",
        southavailability: "September to January",
        time: "All day",
        location: "Pond",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 100,
        cjprice: 150,
        catchphrase: "I caught a tadpole... It's just a tad small.",
        museumphrase: "Undoubtedly you know that tadpoles eventually turn into frogs. I must say, I find them impossibly adorable with their squiggly little tails. But even cuter... when they sprout legs! Why, we can witness accelerated evolution in these squirmy little ones. Hoo, it makes me so emotional!",
        image: "https://acnhapi.com/v1/images/fish/14",
        icon: "https://acnhapi.com/v1/icons/fish/14"
    }, {
        id: 15,
        name: "frog",
        northavailability: "May to August",
        southavailability: "November to February",
        time: "All day",
        location: "Pond",
        rarity: "Common",
        shadow: "Small (2)",
        price: 120,
        cjprice: 180,
        catchphrase: "I caught a frog! Or it's a new neighbor...and I have some apologizing to do.",
        museumphrase: "I understand that frogs converse with fellow frogs through a number of varied calls, as it were. Ribbit! My prince has arrived! Gribbit riiibbit! This pond is tragic! Ribbity rib't! I think you're splendid! Hoo hoo, of course I have no clue what they're saying, but I like to think if I practice enough, I might!",
        image: "https://acnhapi.com/v1/images/fish/15",
        icon: "https://acnhapi.com/v1/icons/fish/15"
    }, {
        id: 16,
        name: "freshwater goby",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "4pm to 9am",
        location: "River",
        rarity: "Common",
        shadow: "Small (2)",
        price: 400,
        cjprice: 600,
        catchphrase: "I caught a freshwater goby! Time to go bye-bye!",
        museumphrase: "The freshwater goby is an unassuming specimen. But beneath that calm, fish exterior, true gluttony resides! It will eat anything that will fit in its mouth...And its mouth is quite the gaping maw, so I recommend you refrain from drawing attention to yourself!",
        image: "https://acnhapi.com/v1/images/fish/16",
        icon: "https://acnhapi.com/v1/icons/fish/16"
    }, {
        id: 17,
        name: "loach",
        northavailability: "March to May",
        southavailability: "September to November",
        time: "All day",
        location: "River",
        rarity: "Common",
        shadow: "Small (2)",
        price: 400,
        cjprice: 600,
        catchphrase: "I caught a loach! It's...looking at me with reproach.",
        museumphrase: "Loaches are a large group of bottom-feeding freshwater fish. Because there are so many species, it is difficult to generalize about them all. The one thing they all have in common is perhaps their most unappealing trait; the name 'loach.' Repellent, isn't it? They should have just called it the 'cockloach' and been done with it, eh wot! Loach...loach... It just tastes terrible in the beak.",
        image: "https://acnhapi.com/v1/images/fish/17",
        icon: "https://acnhapi.com/v1/icons/fish/17"
    }, {
        id: 18,
        name: "catfish",
        northavailability: "May to October",
        southavailability: "November to April",
        time: "4pm to 9am",
        location: "Pond",
        rarity: "Common",
        shadow: "Medium (4)",
        price: 800,
        cjprice: 1200,
        catchphrase: "I caught a catfish! I'm more of a dogfish person...",
        museumphrase: "Catfish don't have scales and are rather slimy. Believe it or not, this slime helps them breathe! Some species of catfish are nocturnal, and they'll feed on almost anything. They use a suctioning action to pull in their food. Did I mention they can grow as large as you or I?",
        image: "https://acnhapi.com/v1/images/fish/18",
        icon: "https://acnhapi.com/v1/icons/fish/18"
    }, {
        id: 19,
        name: "giant snakehead",
        northavailability: "June to August",
        southavailability: "December to February",
        time: "9am to 4pm",
        location: "Pond",
        rarity: "Rare",
        shadow: "Large (5)",
        price: 5500,
        cjprice: 8250,
        catchphrase: "I caught a giant snakehead! Um...but I asked for a medium?",
        museumphrase: "The giant snakehead is quite a sight to behold, wot! One glance conjurs up visions of its namesake. This resilient creature can even find a home in the mud, where it is able to breathe. As a matter of fact, it dislikes cold weather, so during wintertime the mud serves as its temporary home. I hear that they eat anything that swims past their head. While odd, I feel a sense of owlship with them.",
        image: "https://acnhapi.com/v1/images/fish/19",
        icon: "https://acnhapi.com/v1/icons/fish/19"
    }, {
        id: 20,
        name: "bluegill",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "9am to 4pm",
        location: "River",
        rarity: "Common",
        shadow: "Small (2)",
        price: 180,
        cjprice: 270,
        catchphrase: "I caught a bluegill! Do you think it calls me pinklung",
        museumphrase: "The bluegill is incredibly common. A bit too common, depending upon where you are. They eat anything that fits in their mouths and are highly adaptable. The bane of fishermen in some areas, bluegill is often the only fish to be caught! But looking in its wee beady eyes, I must say I see no ill will in it...",
        image: "https://acnhapi.com/v1/images/fish/20",
        icon: "https://acnhapi.com/v1/icons/fish/20"
    }, {
        id: 21,
        name: "yellow perch",
        northavailability: "October to March",
        southavailability: "April to September",
        time: "All day",
        location: "River",
        rarity: "Common",
        shadow: "Medium (3)",
        price: 300,
        cjprice: 450,
        catchphrase: "I caught a yellow perch! Those yellow birds have to sit somewhere!",
        museumphrase: "The yellow perch is certainly worth squawking about. I find it a sight to behold! That jagged dorsal fin! Those brilliant stripes! Those glorious colours! Hoo, truly it is quite the specimen. I would be thrilled to witness it firsthand in its natural environment... But the yellow perch's peak season is winter, I'm afraid. (So very afraid... of winter's biting chill...)",
        image: "https://acnhapi.com/v1/images/fish/21",
        icon: "https://acnhapi.com/v1/icons/fish/21"
    }, {
        id: 22,
        name: "black bass",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "River",
        rarity: "Common",
        shadow: "Medium (4)",
        price: 400,
        cjprice: 600,
        catchphrase: "I caught a black bass! The most metal of all fish!",
        museumphrase: "The black bass is a formidably strong fish and, as such, is a common target for sport anglers. In some areas, there are even those who professionally catch just black bass! Yet in other areas where they are NOT native, they are considered an ecological nuisance. Invasive, even. One cannot help but wonder who is to blame for their invasion, hoo.",
        image: "https://acnhapi.com/v1/images/fish/22",
        icon: "https://acnhapi.com/v1/icons/fish/22"
    }, {
        id: 23,
        name: "tilapia",
        northavailability: "June to October",
        southavailability: "December to April",
        time: "All day",
        location: "River",
        rarity: "Common",
        shadow: "Medium (3)",
        price: 800,
        cjprice: 1200,
        catchphrase: "I caught a tilapia! It makes me happy-a!",
        museumphrase: "Wherever the waters are warm, the tilapia can be found. It is a highly adaptable river fish. They mainly feed on algae, but they will also eat larvae and dead fish— or whatever fits in their mouths. I will confess that, as a growing owlet, I similarly defined food as 'anything that fits in my beak.'",
        image: "https://acnhapi.com/v1/images/fish/23",
        icon: "https://acnhapi.com/v1/icons/fish/23"
    },
    {
        id: 24,
        name: "pike",
        northavailability: "September to December",
        southavailability: "March to June",
        time: "All day",
        location: "River",
        rarity: "Uncommon",
        shadow: "Large (5)",
        price: 1800,
        cjprice: 2700,
        catchphrase: "I caught a pike! Think a swordfish would be up for a duel?",
        museumphrase: "The pike has always reminded me a bit of salmon, although a pike can grow rather larger. These brutes can grow to over four feet long, sometimes MUCH over! Hoo hoo! It is carnivorous and preys not only on other fish, but also mammals and some waterfowl. If I were to ever meet one in the water, I would have a most difficult time keeping my wits about me.",
        image: "https://acnhapi.com/v1/images/fish/24",
        icon: "https://acnhapi.com/v1/icons/fish/24"
    }, {
        id: 25,
        name: "pond smelt",
        northavailability: "December to February",
        southavailability: "June to August",
        time: "All day",
        location: "River",
        rarity: "Common",
        shadow: "Small (2)",
        price: 400,
        cjprice: 600,
        catchphrase: "I caught a pond smelt! Whoever smelt it dealt it!",
        museumphrase: "For many, thinking of pond smelt inevitably leads to thoughts of ice fishing in frozen rivers and lakes. Ice fishing involves making a round hole in the ice, dropping in your fishing line, and...waiting. Not to rain on anyone else's idea of fun, but...well, perhaps I shouldn't say anything.",
        image: "https://acnhapi.com/v1/images/fish/25",
        icon: "https://acnhapi.com/v1/icons/fish/25"
    }, {
        id: 26,
        name: "sweetfish",
        northavailability: "July to September",
        southavailability: "January to March",
        time: "All day",
        location: "River",
        rarity: "Common",
        shadow: "Medium (3)",
        price: 900,
        cjprice: 1350,
        catchphrase: "I caught a sweetfish! Hope it's not artificially sweet!",
        museumphrase: "Sweetfish are the damp heralds of summer! These slippery fellows appear in numbers when it warms up. They hatch in a river, then swim to the ocean. Once mature, they return to the river where they were born. But when they return depends on the river temperature— if it's too cold their fishing season will start later. Some even say summer can't start without sweetfish despite the KEY role played by the earth's axial tilt!",
        image: "https://acnhapi.com/v1/images/fish/26",
        icon: "https://acnhapi.com/v1/icons/fish/26"
    }, {
        id: 27,
        name: "cherry salmon",
        northavailability: "March to June and September to November",
        southavailability: "March to May and September to December",
        time: "4pm to 9am",
        location: "River (Clifftop)",
        rarity: "Common",
        shadow: "Medium (3)",
        price: 1000,
        cjprice: 1500,
        catchphrase: "I caught a cherry salmon! It's the perfect topper for a marlin sundae!",
        museumphrase: "The cherry salmon is related to the salmon, and is known for its distinctive pattern of \"polka dots\". There polka dots disappear as they mature, but ONLY in the first of certain geographic regions. Pity the poor researchers that must make sense of the cherry salmon's fickle fashion sense.",
        image: "https://acnhapi.com/v1/images/fish/27",
        icon: "https://acnhapi.com/v1/icons/fish/27"
    }, {
        id: 28,
        name: "char",
        northavailability: "March to June and September to November",
        southavailability: "March to May to September to December",
        time: "4pm to 9am",
        location: "River (Clifftop) and Pond",
        rarity: "Unommon",
        shadow: "Medium (3)",
        price: 3000,
        cjprice: 5700,
        catchphrase: "I caught a char! Now I'm gonna sit on it!",
        museumphrase: "The char is one of the bigger first around the world, and, in the world of fish, that's quite an accomplishment! They are territorial predators, and therefore must constantly defend their 'turf' from others. So when you see a large char like this one, it is likely a skilled fighter and veteran of many battles. My feathers! I hope it never has cause to go into battle with me!",
        image: "https://acnhapi.com/v1/images/fish/28",
        icon: "https://acnhapi.com/v1/icons/fish/28"
    }, {
        id: 29,
        name: "golden trout",
        northavailability: "March to May & September to November",
        southavailability: "March to May & September to November",
        time: "4pm to 9am",
        location: "River (Clifftop)",
        rarity: "Ultra-rare",
        shadow: "Medium (3)",
        price: 15000,
        cjprice: 22500,
        catchphrase: "I caught a golden trout! But the real treasure? Friendship.",
        museumphrase: "The golden trout is a beautifully colored fish that can only live in very clean waters. They are difficult to come across since they are found only in high mountain streams. As a side note, I find it much easier to appreciate fish that aren't such prima donnas about everything.",
        image: "https://acnhapi.com/v1/images/fish/29",
        icon: "https://acnhapi.com/v1/icons/fish/29"
    }, {
        id: 30,
        name: "stringfish",
        northavailability: "December to March",
        southavailability: "June to September",
        time: "4pm to 9am",
        location: "River (Clifftop)",
        rarity: "Ultra-rare",
        shadow: "Large (5)",
        price: 15000,
        cjprice: 22500,
        catchphrase: "OH MY GOSH! I caught a stringfish! Five more and I'll have a guitarfish!",
        museumphrase: "The stringfish grows slowly, but also lives quite a long time for a fish, with up to 15 years being typical. Consequently, while it takes a while, they can get quite large-perhaps even up to six feet long! The stringfish is perhaps the best embodiment in the fish world of 'slow and steady wins the race'",
        image: "https://acnhapi.com/v1/images/fish/30",
        icon: "https://acnhapi.com/v1/icons/fish/30"
    }, {
        id: 31,
        name: "salmon",
        northavailability: "September",
        southavailability: "March",
        time: "All day",
        location: "River (Mouth)",
        rarity: "Common",
        shadow: "Medium (4)",
        price: 700,
        cjprice: 1050,
        catchphrase: "I caught a salmon! It's all upstream from here!",
        museumphrase: "Ah, salmon! Did you know their coloration is due specifically to their diet? Indeed, this is the case! The more they fill their diet with crustaceans such as krill and shrimp, the deeper shade of pink they are. If they ate a bushel of carrots, might they turn orange?",
        image: "https://acnhapi.com/v1/images/fish/31",
        icon: "https://acnhapi.com/v1/icons/fish/31"
    }, {
        id: 32,
        name: "king salmon",
        northavailability: "September",
        southavailability: "March",
        time: "All day",
        location: "River (Mouth)",
        rarity: "Uncommon",
        shadow: "Largest (6)",
        price: 1800,
        cjprice: 2700,
        catchphrase: "WOO-HOO! I caught a King salmon! Checkmate!",
        museumphrase: "The king salmon didn't get its name for nothing.This stately fish can weigh in at up to 130 pounds! It's clear why it's referred to as the king of salmon. I imagine even the mightiest net can catch no more than a few at a time.I must say it's a miracle to me that you didn't get dragged out to sea by this one, wot!",
        image: "https://acnhapi.com/v1/images/fish/32",
        icon: "https://acnhapi.com/v1/icons/fish/32"
    }, {
        id: 33,
        name: "mitten crab",
        northavailability: "September to November",
        southavailability: "March to May",
        time: "4pm to 9am",
        location: "River",
        rarity: "Uncommon",
        shadow: "Small (2)",
        price: 2000,
        cjprice: 3000,
        catchphrase: "I caught a mitten crab! One more and I'm ready for winter!",
        museumphrase: "The mitten crab was named for its impossibly adorable and fuzzy little pincers. These cute crustaceans embark on quite the journey. They're first born in brackish waters. Then they mature in freshwater. Finally, they travel to the ocean to create more mitten crabs!Hoo! How I delight in the thought of thousands of tiny mittened crabs scuttling about!",
        image: "https://acnhapi.com/v1/images/fish/33",
        icon: "https://acnhapi.com/v1/icons/fish/33"
    }, {
        id: 34,
        name: "guppy",
        northavailability: "April to November",
        southavailability: "October to May",
        time: "9am to 4pm",
        location: "River",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 1300,
        cjprice: 1950,
        catchphrase: "I caught a guppy! Welcome to the team, newbie!",
        museumphrase: "Oh my! Would you look at that! Such a beautiful, snazzy little fellow that guppy is! The shape and coloration of guppy fins are all unique. Quite eye-catching, I must say. Do you imagine they host contests for \"most snazzy\"? And...do you suppose I might receive an invite?",
        image: "https://acnhapi.com/v1/images/fish/34",
        icon: "https://acnhapi.com/v1/icons/fish/34"
    },
    {
        id: 35,
        name: "nibble fish",
        northavailability: "May to September",
        southavailability: "November to March",
        time: "9am to 5pm",
        location: "River",
        rarity: "Uncommon",
        shadow: "Smallest (1)",
        price: 1500,
        cjprice: 2250,
        catchphrase: "I caught a nibble fish! Come to think of it, I could use a bite!",
        museumphrase: "Nibble fish are best known for their use in a certain skin treatment. This treatment has apparently been used for thousands of years. I have never experienced said treatment because they eat your dead skin with their little toothless mouths! Can you imagine anything so repellent?! Please don't ask me any follow-up questions. Hoo.",
        image: "https://acnhapi.com/v1/images/fish/35",
        icon: "https://acnhapi.com/v1/icons/fish/35"
    }, {
        id: 36,
        name: "angelfish",
        northavailability: "May to October",
        southavailability: "November to April",
        time: "4pm to 9am",
        location: "River",
        rarity: "Uncommon",
        shadow: "Small (2)",
        price: 3000,
        cjprice: 4500,
        catchphrase: "I caught an angelfish! That other fish told me to do it!",
        museumphrase: "The angelfish is truly a beautiful creature. Just look at the elegance of those fins!Despite the name, however, these lovelies are known to be rather aggressive. They've no qualms about relentlessly pursuing fish much smaller than themselves! Why, they even attack their own kin! It seems no fish is safe around these angelic bullies. It makes one wonder who comes up with these names. Appearances— and names— can be deceiving.",
        image: "https://acnhapi.com/v1/images/fish/36",
        icon: "https://acnhapi.com/v1/icons/fish/36"
    }, {
        id: 37,
        name: "betta",
        northavailability: "May to October",
        southavailability: "November to April",
        time: "9am to 4pm",
        location: "River",
        rarity: "Uncommon",
        shadow: "Small (2)",
        price: 2500,
        cjprice: 3750,
        catchphrase: "I caught a betta! I betta not drop it!",
        museumphrase: "The betta has long fins and beautiful coloring. It is a tropical fish popular in decorative aquariums. They're very territorial and will fight to complete exhaustion, so aquarists must keep them carefully. Rarely do such beauty and violence commingle outside the rowdiest of sunset-viewing parties.",
        image: "https://acnhapi.com/v1/images/fish/37",
        icon: "https://acnhapi.com/v1/icons/fish/37"
    }, {
        id: 38,
        name: "neon tetra",
        northavailability: "April to November",
        southavailability: "October to May",
        time: "9am to 4pm",
        location: "River",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 500,
        cjprice: 750,
        catchphrase: "I caught a neon tetra! Wasn't hard to track.",
        museumphrase: "Hoo! Wonderful! The neon tetra is truly a marvel of the tropical-fish world. Just look at how tiny it is! And how very filled with...neon! I imagine its environment must be just as flashy as it is for it to have developed such colors. I wonder how flashy I might be, had I been raised somewhere even half as vibrant?",
        image: "https://acnhapi.com/v1/images/fish/38",
        icon: "https://acnhapi.com/v1/icons/fish/38"
    }, {
        id: 39,
        name: "rainbowfish",
        northavailability: "May to October",
        southavailability: "November to April",
        time: "9am to 4pm",
        location: "River",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 800,
        cjprice: 1200,
        catchphrase: "I caught a rainbowfish! Where's my pot of goldfish?",
        museumphrase: "The rainbowfish is a tropical fish known for its metallic colors and beautiful fins. There are over 50 different species, each unique and pleasing color. I must say, it does make me wish for feathers of a more exciting hue than underbaked brownie.",
        image: "https://acnhapi.com/v1/images/fish/39",
        icon: "https://acnhapi.com/v1/icons/fish/39"
    }, {
        id: 40,
        name: "piranha",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "9am to 4pm and 9pm to 4am",
        location: "River",
        rarity: "Rare",
        shadow: "Small (2)",
        price: 2500,
        cjprice: 3750,
        catchphrase: "I caught a piranha! Sure hope it was the only one!",
        museumphrase: "I am not exactly a fan of the piranha, despite knowing that they're mostly harmless. But those nasty, pointy teeth, Hoo. These infamous little blighters will attack when in groups. Imagine all of those hundreds of tiny teeth! To think that they're floundering about our peaceful waters, just waiting to strike. Well, never fear— I shall keep THIS one under the strictest lock and key, with nary a bathroom break allowed!",
        image: "https://acnhapi.com/v1/images/fish/40",
        icon: "https://acnhapi.com/v1/icons/fish/40"
    }, {
        id: 41,
        name: "arowana",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "All day",
        location: "River",
        rarity: "Rare",
        shadow: "Medium (4)",
        price: 10000,
        cjprice: 15000,
        catchphrase: "I caught an arowana! I'd make a joke, but I don't 'wana.",
        museumphrase: "It would seem your angling expertise knows no bounds! This beauteous arowana fetches a pretty Bell, though I'd venture to say that its true price is beyond measure. The arowana has been on the endangered-species list for some time. It's up to us to remain educated and do all we can to help preserve such magnificent creatures. Not to worry, old bean. This lovely fishy friend is in good wings here! On behalf of the museum, I thank you warmly for your unending generosity!",
        image: "https://acnhapi.com/v1/images/fish/41",
        icon: "https://acnhapi.com/v1/icons/fish/41"
    }, {
        id: 42,
        name: "dorado",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "4am to 9pm",
        location: "River",
        rarity: "Ultra-rare",
        shadow: "Large (5)",
        price: 15000,
        cjprice: 22500,
        catchphrase: "I caught a dorado! I say dorado, you say doraydo.",
        museumphrase: "Woo-hoo! So shiny! This massive fish's name, dorado, means \"golden\" in Spanish— a fitting title. They are also quite valuable, I understand. I congratulate you on your top-notch angling! They are rather large, eh wot? It makes one wonder what all they might feed on... Fowl, perhaps?! One quivers at the very thought! Well, it'll be safe behind glass, no doubt. Quite safe, hoo",
        image: "https://acnhapi.com/v1/images/fish/42",
        icon: "https://acnhapi.com/v1/icons/fish/42"
    }, {
        id: 43,
        name: "gar",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "4pm to 9am",
        location: "Pond",
        rarity: "Rare",
        shadow: "Large (5)",
        price: 6000,
        cjprice: 9000,
        catchphrase: "I caught a gar! Yar! It's a gar! Har har!",
        museumphrase: "Hoo hoo! So you have snagged a gar. Did you know this beastly fish can grow up to nine feet long? Indeed, the gar is a remnant of times long past— a living fossil, if you will. It not only has sharp teeth and armor-like scalesn, it has the ability to take breaths of air as well! Ah, to look upon this unusual fish is to get a glimpse of our prehistoric past.",
        image: "https://acnhapi.com/v1/images/fish/43",
        icon: "https://acnhapi.com/v1/icons/fish/43"
    }, {
        id: 44,
        name: "arapaima",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "4pm to 9am",
        location: "River",
        rarity: "Rare",
        shadow: "Largest (6)",
        price: 10000,
        cjprice: 15000,
        catchphrase: "I caught an arapaima! How did it get here? Arapaiknow!",
        museumphrase: "The stately arapaima is quite large. Indeed, it is among the largest freshwater fish there are. Furthermore, these fascinating fish make quite the family unit. That is to say, male arapaimas protect their young by holding them gently in their mouths. Meanwhile, female arapaimas swim circles around these full-mouthed fathers fending off predators. It simply goes to show that cold-blooded creatures can be heartwarming too.",
        image: "https://acnhapi.com/v1/images/fish/44",
        icon: "https://acnhapi.com/v1/icons/fish/44"
    }, {
        id: 45,
        name: "saddled bichir",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "9pm - 4am",
        location: "River",
        rarity: "Uncommon",
        shadow: "Medium (4)",
        price: 4000,
        cjprice: 6000,
        catchphrase: "Wow! A saddled bichir! And me without my tiny riding crop...",
        museumphrase: "What an elegant specimen you've found. The saddled bichir has a look entirely its own. They have poor eyesight, so they use their fine-tuned sniffers to seek out prey. Can you imagine relying solely on your sense of smell to find food? And if one nostril became clogged, would you be unable to tell how far away the scent was?",
        image: "https://acnhapi.com/v1/images/fish/45",
        icon: "https://acnhapi.com/v1/icons/fish/45"
    },
    {
        id: 46,
        name: "sturgeon",
        northavailability: "September to March",
        southavailability: "March to September",
        time: "All day",
        location: "River (Mouth)",
        rarity: "Uncommon",
        shadow: "Largest (6)",
        price: 10000,
        cjprice: 15000,
        catchphrase: "I caught a sturgeon! Wonder if it can perform sturgery...",
        museumphrase: "The sturgeon is a large and long-lived fish which has changed little in the last 300 million years. One curious behavior of theirs is leaping high out of the water and falling back in on their sides. The smacking sounds of their re-entry can be heard for up to half a mile away, likely more underwater! No one knows why they do it, but I like to think it's their impression of bread popping out of a toaster!",
        image: "https://acnhapi.com/v1/images/fish/46",
        icon: "https://acnhapi.com/v1/icons/fish/46"
    }, {
        id: 47,
        name: "sea butterfly",
        northavailability: "December to March",
        southavailability: "June to September",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 1000,
        cjprice: 1500,
        catchphrase: "I caught a sea butterfly! Try not to confuse it for a sea moth!",
        museumphrase: "Such mystery! Such grace! Did you know that the sea butterfly's scientific name is Thecosomata? A very rough translation of that is 'shell body.' Indeed, this illustrious creature is related to snails! However, it reminds me much more of an elegant feathered friend, the way it flies through the water. With such grace in flying, one shouldn't wonder if it's related to the owl, hoo hoo!",
        image: "https://acnhapi.com/v1/images/fish/47",
        icon: "https://acnhapi.com/v1/icons/fish/47"
    }, {
        id: 48,
        name: "sea horse",
        northavailability: "April to November",
        southavailability: "October to May",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 1100,
        cjprice: 1650,
        catchphrase: "I caught a sea horse! But...where's its sea jockey?",
        museumphrase: "Ah, a favorite of mine, to be sure! The sea horse is such a very unique creature and is indeed a fish! Though, as far as fish go, sea horses are not great swimmers. The sea horse, you see, has but a wee fin on its back, which propels it through water rather poorly. Thus these fish are often found using their prehensile tails to hold tight in amongst the sea grass. And here's one final fact for you... Sea horses have no stomach and so must constantly feed to stay alive! Indeed, the life of a land horse sounds far easier than that of the hardworking horse of the sea.",
        image: "https://acnhapi.com/v1/images/fish/48",
        icon: "https://acnhapi.com/v1/icons/fish/48"
    }, {
        id: 49,
        name: "clownfish",
        northavailability: "April to September",
        southavailability: "October to March",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Smallest (1)",
        price: 650,
        cjprice: 975,
        catchphrase: "I caught a clown fish! How many can fit in a carfish?",
        museumphrase: "Few can deny the delightful qualities of the clown fish. These vibrant fishes make their home among venomous anemones. It's a mutually beneficial arrangement. The clown fish finds safety in the anemone's wriggling arms, as well as leftover scraps of food. In return, clown fish ward off parasites and predators for the anemone. Thus these colorful fish remind us of the importance of maintaining good cheer among our roommates.",
        image: "https://acnhapi.com/v1/images/fish/49",
        icon: "https://acnhapi.com/v1/icons/fish/49"
    }, {
        id: 50,
        name: "surgeonfish",
        northavailability: "April to September",
        southavailability: "October to March",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Smallest (2)",
        price: 1000,
        cjprice: 1500,
        catchphrase: "I caught a surgeonfish! Scalpel! Forceps! Fish hook!",
        museumphrase: "Hoo! Careful, now! These fish are particularly dangerous, despite their seemingly docile appearance. With its saturated blue and yellow tones, the surgeonfish is quite breathtaking. It's got to keep up with all the other vibrant fish that live in the coral too, I wager. Quite the competition! Its spine is sharp as a blade, so care must be taken when handling these beauties...",
        image: "https://acnhapi.com/v1/images/fish/50",
        icon: "https://acnhapi.com/v1/icons/fish/50"
    }, {
        id: 51,
        name: "butterfly fish",
        northavailability: "April to September",
        southavailability: "October to March",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Small (2)",
        price: 1000,
        cjprice: 1500,
        catchphrase: "I caught a butterfly fish! Did it change from a caterpillar fish?",
        museumphrase: "Ah, the butterfly fish is just charming with its beautiful colors and elegant movements. I refer to it as a butterfly fish, but it's actually a grouping in which there are over 100 types! These beautiful aquatic friends swim in schools amid coral, fluttering back and forth with the tides. The sheer awe one must experience when witnessing such a sight. It must be a dream! So much better than actual butterflies...",
        image: "https://acnhapi.com/v1/images/fish/51",
        icon: "https://acnhapi.com/v1/icons/fish/51"
    }, {
        id: 52,
        name: "napoleonfish",
        northavailability: "July to August",
        southavailability: "January to February",
        time: "4am to 9pm",
        location: "Sea",
        rarity: "Rare",
        shadow: "Largest (6)",
        price: 10000,
        cjprice: 15000,
        catchphrase: "I caught a Napoleonfish! It's not as big as it thinks!",
        museumphrase: "Quite the catch you've brought! The stately and debonair Napoleonfish is truly something to behold. Those beady eyes! That bumpy head! That bold blue-green coloring! Alas, this quirky creature is quite endangered due to a variety of factors. Needless to say, we must do our very best to take care of our lumpy friend and its environment.",
        image: "https://acnhapi.com/v1/images/fish/52",
        icon: "https://acnhapi.com/v1/icons/fish/52"
    }, {
        id: 53,
        name: "zebra turkeyfish",
        northavailability: "April to November",
        southavailability: "October to May",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Medium (3)",
        price: 500,
        cjprice: 750,
        catchphrase: "I caught a zebra turkeyfish! Land, air, water--make up your mind!",
        museumphrase: "The sheer brilliance and diversity found in the aquatic underworld never cease to amaze me. This zebra turkeyfish is as stunning to gaze upon as it is deadly. Those spines that are part of its defining physique are chock-full of venom. Fortunately, zebra turkeyfish are not susceptible to another's venom. Though solitary, I imagine they give one another a mean fin bump when passing each other by.",
        image: "https://acnhapi.com/v1/images/fish/53",
        icon: "https://acnhapi.com/v1/icons/fish/53"
    }, {
        id: 54,
        name: "blowfish",
        northavailability: "November to February",
        southavailability: "May to August",
        time: "9pm to 4am",
        location: "Sea",
        rarity: "Uncommon",
        shadow: "Medium (3)",
        price: 5000,
        cjprice: 7500,
        catchphrase: "I caught a blowfish! I'm blown away!",
        museumphrase: "As you may know, blowfish carry a deadly poison and are among the most toxic creatures on earth. What you may not have known is that poison and spines are not the limit of this animal's defenses! A predator that tries to swallow a blowfish before it inflates can find itself quickly choking. To be honest, if said predator can get past poison, spines, AND choking hazards, I feel they've earned a meal.",
        image: "https://acnhapi.com/v1/images/fish/54",
        icon: "https://acnhapi.com/v1/icons/fish/54"
    }, {
        id: 55,
        name: "puffer fish",
        northavailability: "July to September",
        southavailability: "January to March",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Medium (3)",
        price: 250,
        cjprice: 375,
        catchphrase: "I caught a puffer fish! I thought you would be tougher, fish!",
        museumphrase: "Like its cousin the blowfish, when the puffer fish feels threatened it inflates into a spiky balloon. The biggest difference between them is that the puffer fish is not deadly poisonous like its kin. So while it may look scary, the substantially reduced risk to life and limb makes it much better company.",
        image: "https://acnhapi.com/v1/images/fish/55",
        icon: "https://acnhapi.com/v1/icons/fish/55"
    }, {
        id: 56,
        name: "anchovy",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "4am to 9pm",
        location: "Sea",
        rarity: "Common",
        shadow: "Small (2)",
        price: 200,
        cjprice: 300,
        catchphrase: "I caught an anchovy! Stay away from my pizza!",
        museumphrase: "There are more than 140 species of anchovy, but they do all have some things in common. They are small and feed by simply swimming with their mouths open to filter food particles from the sea. (In my sleepier moments, I sometimes wish I could do that...)",
        image: "https://acnhapi.com/v1/images/fish/56",
        icon: "https://acnhapi.com/v1/icons/fish/56"
    },
    {
        id: 57,
        name: "horse mackerel",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Small (2)",
        price: 150,
        cjprice: 225,
        catchphrase: "I caught a horse mackerel! Of course, Mack...er...el.",
        museumphrase: "Supposedly the horse mackerel derives its name from a-false-myth about its strengh as a swimmer. The gist of it is that these fish are so powerful underwater that smaller fish can ride them as steeds! It's absurd, of course. Where would these alleged fish jockeys attach a saddle, much less horseshoes? One does wish that people would construct their legends with a BIT more scientific plausibility!",
        image: "https://acnhapi.com/v1/images/fish/57",
        icon: "https://acnhapi.com/v1/icons/fish/57"
    }, {
        id: 58,
        name: "barred_knifejaw",
        northavailability: "March to November",
        southavailability: "September to May",
        time: "All day",
        location: "Sea",
        rarity: "Uncommon",
        shadow: "Medium (3)",
        price: 5000,
        cjprice: 7500,
        catchphrase: "I caught a barred knifejaw! They must have a hard time eating!",
        museumphrase: "Wonderful! I would love nothing more! The barred knifejaw, also called the striped beakfish, is a lovely fish with a distinctive striped pattern. It is reportedly also a very curious fish in that it has been known to approach swimmers to \"greet\" them. They also tend to be good at avoiding fishing hooks, so well done on outwitting this one!",
        image: "https://acnhapi.com/v1/images/fish/58",
        icon: "https://acnhapi.com/v1/icons/fish/58"
    }, {
        id: 59,
        name: "sea bass",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Large (5)",
        price: 400,
        cjprice: 600,
        catchphrase: "I caught a sea bass! No, wait- it's at least a C+!",
        museumphrase: "Sea bass is a name given to a variety of different species of saltwater fish. They are a varied bunch with some as small as four inches and some as staggeringly ginormous as eight feet! 'Sea bass' is a bit pedestrian though. Many species have better names, such as 'redbanded perch.' Or the delightfully whimsical dusky grouper! Or the potato cod! WILL NO ONE THINK OF THE PINK MAOMAO?!",
        image: "https://acnhapi.com/v1/images/fish/59",
        icon: "https://acnhapi.com/v1/icons/fish/59"
    }, {
        id: 60,
        name: "red snapper",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Medium (4)",
        price: 3000,
        cjprice: 4500,
        catchphrase: "I caught a red snapper! It looks pretty dapper!",
        museumphrase: "Red snapper is the common name of dozens of fish species, and I wonder why it is so popular. Are there so many types of fish that are both a shade of red and have a tendency to snap? Were there no other names? What about 'burgundy biter'? 'Garnet grasper'? 'Puce pincher'?",
        image: "https://acnhapi.com/v1/images/fish/60",
        icon: "https://acnhapi.com/v1/icons/fish/60"
    }, {
        id: 61,
        name: "dab",
        northavailability: "October to April",
        southavailability: "April to October",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Medium (3)",
        price: 300,
        cjprice: 450,
        catchphrase: "I caught a dab! Not bad!",
        museumphrase: "The dab is a flatfish that bears some resemblance to the olive flounder, though their mouths are different. Personally, I am morbidly fascinated by each fish's eye placement. The dab's eyes are both on its right side, while the olive flounder's are on the left. These fish spend lots of time lying on their sides in the sand, so the odd eye placement makes some sense... But its-how can I put this? Creepy? Viscerally disturbing? Profoundly upsetting to fans of symmetry?",
        image: "https://acnhapi.com/v1/images/fish/61",
        icon: "https://acnhapi.com/v1/icons/fish/61"
    }, {
        id: 62,
        name: "olive flounder",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Large (5)",
        price: 800,
        cjprice: 1200,
        catchphrase: "I caught an olive flounder! That's not the pits!",
        museumphrase: "Did you know that the olive flounder is the same shape as other fish when it hatches? But as it grows, it gets both wider and flatter, and can reach some three feet long. These flat fish spend much of their lives buried under the sandy ocean floor, waiting for prey to happen by. Imagine the surprise for said prey when they strike. It would be as if your kitchen floor were to bite you.",
        image: "https://acnhapi.com/v1/images/fish/62",
        icon: "https://acnhapi.com/v1/icons/fish/62"
    }, {
        id: 63,
        name: "squid",
        northavailability: "December to August",
        southavailability: "June to February",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Medium (3)",
        price: 500,
        cjprice: 750,
        catchphrase: "I caught a squid! It's off the hook! (I had an inkling I might!) (Do they...not actually bloop?)",
        museumphrase: "Well, first off, squids are members of the mollusk family, just like the octopus. Many mollusks like snails and clams have shells, but the squid's body is almost completely soft. The exception is a long, narrow bit of hard material going through its main body - the last remnant of its shell. Of course, having your shell INSIDE is not a best practice. Perhaps they lost the owner's manual!",
        image: "https://acnhapi.com/v1/images/fish/63",
        icon: "https://acnhapi.com/v1/icons/fish/63"
    }, {
        id: 64,
        name: "moray eel",
        northavailability: "August to October",
        southavailability: "February to April",
        time: "All day",
        location: "Sea",
        rarity: "Uncommon",
        shadow: "Narrow",
        price: 2000,
        cjprice: 3000,
        catchphrase: "I caught a moray eel! When you're in love, that's a moray!",
        museumphrase: "Despite its rather frightening features, the moray eel is really a very cowardly fish. It lives its life hiding in caves, and will only attack if you're looking for a fight. You've heard of a \"bark that is worse than the bite\"? Well, the moray eel has a face that's worse than its fight!",
        image: "https://acnhapi.com/v1/images/fish/64",
        icon: "https://acnhapi.com/v1/icons/fish/64"
    }, {
        id: 65,
        name: "ribbon eel",
        northavailability: "June to October",
        southavailability: "December to April",
        time: "All day",
        location: "Sea",
        rarity: "Common",
        shadow: "Narrow",
        price: 600,
        cjprice: 900,
        catchphrase: "I caught a ribbon eel! Can it tie itself into a bow?",
        museumphrase: "The ribbon eel is related to the moray eel, though its bright coloration distinguishes it. It also has an unusual plant-like appendage at the tip of its nose that flutters as the creature moves. I like to think of it as having an extremely friendly nose that waves a greeting to those nearby!",
        image: "https://acnhapi.com/v1/images/fish/65",
        icon: "https://acnhapi.com/v1/icons/fish/65"
    }, {
        id: 66,
        name: "tuna",
        northavailability: "November to April",
        southavailability: "May to October",
        time: "All day",
        location: "Pier",
        rarity: "Rare",
        shadow: "Largest (6)",
        price: 7000,
        cjprice: 10500,
        catchphrase: "I caught a tuna! It's a little off-key!",
        museumphrase: "The tuna is a large ocean fish that can reach upwards of nine feet long. Besides its great size, it's notable for continuing to swim even when it's sleeping! Well, to be fair, if it doesn't keep swimming, it won't be able to breathe and will of course die... But sleep should be restful, eh wot! If I were the tuna I would feel very hard done by!",
        image: "https://acnhapi.com/v1/images/fish/66",
        icon: "https://acnhapi.com/v1/icons/fish/66"
    }, {
        id: 67,
        name: "blue marlin",
        northavailability: "November to April and July to September",
        southavailability: "May to October and January to March",
        time: "All day",
        location: "Pier",
        rarity: "Rare",
        shadow: "Largest (6)",
        price: 10000,
        cjprice: 15000,
        catchphrase: "I caught a blue marlin! Listen to this fish. it's got a point.",
        museumphrase: "The blue marlin has a distinctive angular shape and no scales. It is an unusual relative of the tuna. These mighty fish can exceed 13 feet from bill to tail. Some accounts even have it fighting with whales! No wonder it's a popular target for sport fishing: unlike most fish, it seems like a worthy opponent.",
        image: "https://acnhapi.com/v1/images/fish/67",
        icon: "https://acnhapi.com/v1/icons/fish/67"
    },
    {
        id: 68,
        name: "giant trevlly",
        northavailability: "May to October",
        southavailability: "November to April",
        time: "All day",
        location: "Pier",
        rarity: "Uncommon",
        shadow: "Large (5)",
        price: 4500,
        cjprice: 6750,
        catchphrase: "I caught a giant trevally! Yeah, I'm pretty well-trevalled.",
        museumphrase: "The giant trevally, as befits its name, can reach six feet in length and 180 pounds! Its size and strength have made it a favored opponent for anglers since time immemorial. They are also ingenious hunters, sometimes taking advantage of other predators to distract their prey. There have even been documented cases of them attacking —gulp— birds.",
        image: "https://acnhapi.com/v1/images/fish/68",
        icon: "https://acnhapi.com/v1/icons/fish/68"
    }, {
        id: 69,
        name: "mahi-mahi",
        northavailability: "May to October",
        southavailability: "November to April",
        time: "All day",
        location: "Pier",
        rarity: "Rare",
        shadow: "Large (5)",
        price: 6000,
        cjprice: 9000,
        catchphrase: "I caught a mahi-mahi! It's all mahine-mahine.",
        museumphrase: "The mahi-mahi is an ocean fish known for its wide, somewhat-cute face. It can reach over six feet long. It is known by different names including \"dolphinfish,\" even though it has no relation to dolphins. They live in only in warm, tropical waters...which perhaps explains the relaxed, happy look on their faces.",
        image: "https://acnhapi.com/v1/images/fish/69",
        icon: "https://acnhapi.com/v1/icons/fish/69"
    }, {
        id: 70,
        name: "ocean sunfish",
        northavailability: "July to September",
        southavailability: "January to March",
        time: "4am to 9pm",
        location: "Sea",
        rarity: "Uncommon",
        shadow: "Largest with fin (6)",
        price: 4000,
        cjprice: 6000,
        catchphrase: "I caught an ocean sunfish! Good thing I'm wearing ocean sunscreen!",
        museumphrase: "The ocean sunfish is a large relative of the blowfish with an unusual shape, like a fish head with a tail. They are a fairly relaxed species, often content to ride where the currents take them. This is fortunate as, otherwise, the sight of a large head coming toward you might be alarming!",
        image: "https://acnhapi.com/v1/images/fish/70",
        icon: "https://acnhapi.com/v1/icons/fish/70"
    }, {
        id: 71,
        name: "ray",
        northavailability: "August to November",
        southavailability: "February to May",
        time: "4am to 9pm",
        location: "Sea",
        rarity: "Uncommon",
        shadow: "Large (5)",
        price: 3000,
        cjprice: 4500,
        catchphrase: "I caught a ray! A few more and I'll have a tan!",
        museumphrase: "The ray is an unusually shaped fish with a flat body and a long body, somewhat related to sharks. Seen from the bottom, the mouth on its stomach appears to be smiling, which is objectively adorable. But be cautious—unlike most cute animals, some rays are extremely venomous. BEWARE THE SMILE.",
        image: "https://acnhapi.com/v1/images/fish/71",
        icon: "https://acnhapi.com/v1/icons/fish/71"
    }, {
        id: 72,
        name: "saw shark",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "4pm to 9am",
        location: "Sea",
        rarity: "Rare",
        shadow: "Largest with fin (6)",
        price: 12000,
        cjprice: 18000,
        catchphrase: "I caught a saw shark! You could call it a sea saw!",
        museumphrase: "As you might expect from the name, the saw shark is a shark with a head that resembles a saw. This unusual appendage is used both to dig potential prey out of the sand and as a weapon against said prey. Given that, it seems like a more appropriate name would have been shovel-sword shark, eh wot?",
        image: "https://acnhapi.com/v1/images/fish/72",
        icon: "https://acnhapi.com/v1/icons/fish/72"
    }, {
        id: 73,
        name: "hammerhead shark",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "4pm to 9am",
        location: "Sea",
        rarity: "Uncommon",
        shadow: "Largest with fin (6)",
        price: 8000,
        cjprice: 1200,
        catchphrase: "I caught a hammerhead shark! I hit the nail on the head!",
        museumphrase: "The hammerhead shark is known for its distinctive, hammer-shaped head, hence the name. Er, obviously. Anyhoot, this oddly shaped head allows the beast to see 360 degrees around itself, from top to bottom. Imagine being able to see so widely! You could check for untied shoelaces AND imminent rain simultaneously!",
        image: "https://acnhapi.com/v1/images/fish/73",
        icon: "https://acnhapi.com/v1/icons/fish/73"
    }, {
        id: 74,
        name: "great white shark",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "4pm to 9am",
        location: "Sea",
        rarity: "Rare",
        shadow: "Largest with fin (6)",
        price: 15000,
        cjprice: 22500,
        catchphrase: "I caught a great white shark! Watch out for its jaws!",
        museumphrase: "Great white sharks are obviously known first and foremost for their biting. They are masters of the craft! They do lose teeth regularly through biting-related activities, but, luckily, those teeth grow back quickly. In fact, their missing teeth can be regrown in a single day. Just imagine their tooth-fairy-related income!",
        image: "https://acnhapi.com/v1/images/fish/74",
        icon: "https://acnhapi.com/v1/icons/fish/74"
    }, {
        id: 75,
        name: "whale shark",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "All day",
        location: "Sea",
        rarity: "Rare",
        shadow: "Largest with fin (6)",
        price: 13000,
        cjprice: 19500,
        catchphrase: "Thar she blows! I caught a whale shark! I'm tellin' ya, it was thiiiiiiiiiiiiiiiiiiiis big!",
        museumphrase: "The mighty whale shark is the largest species of fish in the world with specimens up to 60 feet long! Unlike many of their kin in the shark family, whale sharks are nonviolent, eating only plankton and such. They grow slowly and live long, relaxed lives of filter feeding and leisure in warm waters. So if you ever have to choose a fish as a roommate, you could do worse than the whale shark. Unless you can't swim.",
        image: "https://acnhapi.com/v1/images/fish/75",
        icon: "https://acnhapi.com/v1/icons/fish/75"
    }, {
        id: 76,
        name: "suckerfish",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "All day",
        location: "Sea",
        rarity: "Uncommon",
        shadow: "Medium with fin (4)",
        price: 1500,
        cjprice: 2250,
        catchphrase: "I caught a suckerfish! I thought it was a shark! Oh, wait - now I get it.",
        museumphrase: "The suckerfish is a curious fish that likes to attach itself with its sucker mouth to larger marine animals. The benefit to the suckerfish is that it gets to eat smaller parasites and dead skin off the host's body. Amusingly, some people have used suckerfish on cords to catch large turtles with the fish's own suction! I imagine this practice is the cause of some awkward conversations between fish and turtle, eh wot",
        image: "https://acnhapi.com/v1/images/fish/76",
        icon: "https://acnhapi.com/v1/icons/fish/76"
    }, {
        id: 77,
        name: "football fish",
        northavailability: "November to March",
        southavailability: "May to September",
        time: "4pm to 9am",
        location: "Sea",
        rarity: "Uncommon",
        shadow: "Medium (4)",
        price: 2500,
        cjprice: 3750,
        catchphrase: "I caught a football fish! Some countries call it a soccer fish!",
        museumphrase: "The football fish is a strange and grotesque deep-sea fish with a lantern-like light on its forehead. Its light is apparently powered by luminous bacteria and other glowing microorganisms. One theory says it can spray these luminescent sidekicks when prey approaches in order to dazzle them...The deep contains many mysteries...as well as some things that are just sort of odd and off-putting.",
        image: "https://acnhapi.com/v1/images/fish/77",
        icon: "https://acnhapi.com/v1/icons/fish/77"
    }, {
        id: 78,
        name: "oarfish",
        northavailability: "December to May",
        southavailability: "June to November",
        time: "All day",
        location: "Sea",
        rarity: "Rare",
        shadow: "Largest (6)",
        price: 9000,
        cjprice: 13500,
        catchphrase: "I caught an oarfish! I hope I catch morefish!",
        museumphrase: "The oarfish is a long, eel-like fish that can supposedly reach up to 36 feet in length. They appear in various legends as things like messengers of the gods. It seems to me a creature like that could explain the myth of massive, ship-crushing sea serpents. It is, of course, well documented that people tend to exaggerate the size of the one that got away.",
        image: "https://acnhapi.com/v1/images/fish/78",
        icon: "https://acnhapi.com/v1/icons/fish/78"
    },
    {
        id: 79,
        name: "barreleye",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "9pm to 4am",
        location: "Sea",
        rarity: "Ultra-rare",
        shadow: "Small (2)",
        price: 15000,
        cjprice: 22500,
        catchphrase: "I caught a barreleye! Like eyeing fish in a barrel!",
        museumphrase: "The barreleye is a deep-sea fish with protuberant eyes and a clear head, so some of its organs are... visible. At first blush, a transparent head seems absurd, but there is a reason: so it can see things directly above! But I must confess - the more I learn about deep-sea fish, the happier I am to live on dry land, wot.",
        image: "https://acnhapi.com/v1/images/fish/79",
        icon: "https://acnhapi.com/v1/icons/fish/79"
    }, {
        id: 80,
        name: "coelacanth",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        location: "Sea (when raining or snowing)",
        rarity: "Ultra-rare",
        shadow: "Largest (6)",
        price: 15000,
        cjprice: 22500,
        catchphrase: "Blast from the past! I caught a coelacanth! Think positive! Be a coela-CAN!",
        museumphrase: "The coelacanth is a deep-sea fish that has been around since the age of the dinosaurs. They were long thought extinct, so when living specimens were discovered, it was quite a shock! Now I'll just have to figure out where in the museum to display it— fish or fossils!",
        image: "https://acnhapi.com/v1/images/fish/80",
        icon: "https://acnhapi.com/v1/icons/fish/80"
    }
];