export const SEACREATURES = [
    {
        id: 1,
        name: "seaweed",
        northavailability: "October to July",
        southavailability: "April to January",
        time: "All day",
        speed: "Stationary",
        shadow: "Large",
        price: 600,
        catchphrase: "I got some seaweed! I couldn't kelp myself.",
        museumphrase: "Let it be known that seaweed is a misnomer of the highest order! That is, it is not a noxious weed so much as it is a marine algae most beneficial to life on land and sea. Seaweed, you see, provides essential habitat and food for all manner of marine creatures. And it creates a great deal of the oxygen we land lovers love to breath too, hoo! And yet, I can't help but shudder when the slimy stuff touches my toes during a swim. Hoot! The horror!",
        image: "https://acnhapi.com/v1/images/sea/1",
        icon: "https://acnhapi.com/v1/icons/sea/1"
    },
    {
        id: 2,
        name: "sea grapes",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "All day",
        speed: "Stationary",
        shadow: "Small",
        price: 900,
        catchphrase: "I got some sea grapes! Can't let these go sour.",
        museumphrase: "Sea grapes are a marine algae that look much like their landlocked namesake. That is, they are green pearl-like orbs that cluster tightly along underwater vines. And sea grapes, like regular grapes, are a popular snack food too... albeit of the saltier variety. Fans of the briny delicacy enjoy the way the shiny pearls POP when chewed. It makes one wonder whether sea grape juice might have some appeal? 'Twould leave the drinker with sour grapes, I suppose.",
        image: "https://acnhapi.com/v1/images/sea/2",
        icon: "https://acnhapi.com/v1/icons/sea/2"
    },
    {
        id: 3,
        name: "sea cucumber",
        northavailability: "November to April",
        southavailability: "May to October",
        time: "All day",
        speed: "Very slow",
        shadow: "Medium",
        price: 500,
        catchphrase: "I got a sea cucumber! It's a bit cumbersome",
        museumphrase: "The sea cucumber, much like its relatives the sea urchin and sea star, has no heart nor brain. However, unlike its relatives, it has no shell nor spikes to with which to protect itself either. So how does a softy such as this stay safe in the open ocean? Brace yourself I say… when threatened sea cucumbers jettison their innards out of their backsides! Hoo! Gross but true! The sticky, stringy stuff ensnares predators, allowing the cuke to make its escape and grow its insides back. One might say…the sea cucumber is a GUTSY creature, indeed. Hoo hoo, hee hee! Do forgive me!",
        image: "https://acnhapi.com/v1/images/sea/3",
        icon: "https://acnhapi.com/v1/icons/sea/3"
    },
    {
        id: 4,
        name: "sea pig",
        northavailability: "November to February",
        southavailability: "May to August",
        time: "4pm to 9am",
        speed: "Very fast",
        shadow: "Small",
        price: 10000,
        catchphrase: "I got a sea pig! What's next? Air pigs?",
        museumphrase: "Never have I seen a creature that walks the line between creepy and cute quite like the sea pig does. Sea pigs are, in fact, a type of sea cucumber that lives deep down on the ocean floor. About four inches long, these soft pinkish oddities use tube-like legs and feelers to get around. Thus they snuffle through the mud, slurping up particles from decaying carcasses. Meanwhile, predators be warned... This little piggy tastes like poison.",
        image: "https://acnhapi.com/v1/images/sea/4",
        icon: "https://acnhapi.com/v1/icons/sea/4"
    },
    {
        id: 5,
        name: "sea star",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        speed: "Very slow",
        shadow: "Small",
        price: 500,
        catchphrase: "I got a sea star! Maybe it'll give me an autograph!",
        museumphrase: "The sea star may appear to have five feet...but those are, in fact, its arms. And though five-armed sea stars are the most common, there are species with 20 or even 40 arms out there! Ah, but the fascinating appendage fats do not end there, wot wot! You see upon each sea star's arm sprout many dozens of tiny feet. YES, FEET! They use these suction-cupped feet not just to move about...but to...eh... grab hold of dinner guests as well. Finally, it should be noted that when a sea star loses an arm, it can grow it back. More impressive yes, a served sea star arm...can sometimes grow an entire sea star body back!",
        image: "https://acnhapi.com/v1/images/sea/5",
        icon: "https://acnhapi.com/v1/icons/sea/5"
    },
    {
        id: 6,
        name: "sea urchin",
        northavailability: "May to September",
        southavailability: "November to March",
        time: "All day",
        speed: "Slow",
        shadow: "Small",
        price: 1700,
        catchphrase: "I got a sea urchin! Wasn't even 'earchin for it.",
        museumphrase: "Ah, the sea urchin...the unabashed goth of the ocean floor! Indeed, with its mane of dark-hued spikes, it looks for all the world as if it might front a punk-rock band. Perhaps its more demure relatives—the sea cucumber and the sea star—disapprove of its outlandish look? It would certainly explain why sea stars gobble up sea urchins every chance they get! But worry not for our spiky friend. Its venomous spines are an effective deterrent to many a predator.",
        image: "https://acnhapi.com/v1/images/sea/6",
        icon: "https://acnhapi.com/v1/icons/sea/6"
    },
    {
        id: 7,
        name: "slate pencil urchin",
        northavailability: "May to September",
        southavailability: "November to March",
        time: "4pm to 9am",
        speed: "Medium",
        shadow: "Medium",
        price: 2000,
        catchphrase: "I got a slate pencil urchin! Its handwriting is gorgeous.",
        museumphrase: "Slate Pencil Urchins are a type of sea urchin topped with thick, rounded spines that resemble sticks of chalk. These urchins' spines protect them not only from predators but from violent waves as well. Found in coral reefs, they're usually bright red, brown, or purple in color. For all those bright colors, one would think the slate pencil urchin to be deadly. But all those pretty colors, it seems, are just a pretty show.",
        image: "https://acnhapi.com/v1/images/sea/7",
        icon: "https://acnhapi.com/v1/icons/sea/7"
    },
    {
        id: 8,
        name: "sea anemone",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        speed: "Stationary",
        shadow: "Large",
        price: 500,
        catchphrase: "I got a sea anemone! The enemy of my anemone is my afrenome!",
        museumphrase: "Medusa herself would be impressed by the sea anemone. This pretty predator loves to wave its colorful flowing locks about. But these gorgeous tresses are, in fact, deadly tentacles surrounding a hungry mouth! Triggered by the slightest touch, these tentacles harpoon victims with neurotoxin. The sea anemone then pulls the helpless, hapless prey into its mouth for a spot of lunch! I say, let this be a lesson! Never, ever make an enemy... out of an anemone!",
        image: "https://acnhapi.com/v1/images/sea/8",
        icon: "https://acnhapi.com/v1/icons/sea/8"
    },
    {
        id: 9,
        name: "moon jellyfish",
        northavailability: "July to September",
        southavailability: "January to March",
        time: "All day",
        speed: "Very slow",
        shadow: "Small",
        price: 600,
        catchphrase: "I got a moon jellyfish! Now to find a sun peanutbutterfish.",
        museumphrase: "Ah, the moon jellyfish...what's not to love about this pretty floating flower of the sea... Well, I suppose its tentacles do give a sting when touched...but it's only a mild thing to the likes of us. Other creatures may not be so fond of this translucent beauty. Though who can blame them, really? Moon jellyfish have stinging cells called cnidocytes that kill fish and other small critters that float by. And they use their oral arms to pull these morsels into their mouths and stomachs. Indeed, one need but observe the moon jellyfish to see how brutal AND beautiful nature can be.",
        image: "https://acnhapi.com/v1/images/sea/9",
        icon: "https://acnhapi.com/v1/icons/sea/9"
    },
    {
        id: 10,
        name: "sea slug",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        speed: "Very slow",
        shadow: "Smallest",
        price: 600,
        catchphrase: "I got a sea slug! It's kinda salty about that.",
        museumphrase: "Imagine, if you will, a land slug...but one dressed in frilly attire full of bold colors, stripes, and spots! That is the sea slug, a gastropod that looks ready to walk the red carpet...or perform beneath a big top. But these clowns are no laughing matter, eh wot. Their garish colors and wild patterns warn predators to steer clear of their stinging, toxic taste. And THAT is how you dress for success, as they say!",
        image: "https://acnhapi.com/v1/images/sea/10",
        icon: "https://acnhapi.com/v1/icons/sea/10"
    },
    {
        id: 11,
        name: "pearl oyster",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        speed: "Medium",
        shadow: "Small",
        price: 2800,
        catchphrase: "I got a pearl oyster! Aw, shucks. Don't clam up now!",
        museumphrase: "Hoo, indeed, hoot! What a splendid pearl oyster! Did you know the famed pearl oyster can live for 40 years and grow up to a foot in size? 'Tis true, hootie-hoo! Of course, this briny bivalve is best known for the precious gems it grows within. The pearl-making process begins when an irritant gains access to the delicate insides of the oyster. The intruder is then covered with layer upon layer of nacre, the same substance used to create its shell. It takes years for a pearl to form, but in the end, the irritant is rendered harmless. Ahh, if only we all had the power to turn things that annoy us... into things of beauty instead.",
        image: "https://acnhapi.com/v1/images/sea/11",
        icon: "https://acnhapi.com/v1/icons/sea/11"
    },
    {
        id: 12,
        name: "mussel",
        northavailability: "June to December",
        southavailability: "December to June",
        time: "All day",
        speed: "Slow",
        shadow: "Small",
        price: 1500,
        catchphrase: "I got a mussel! It's been working out",
        museumphrase: "Did you know the mussel has a beard?! Hoo! It's true! Well, partially true, anyway. Mussels have a special gland that secretes a thing called \"bysuss\" or \"byssal thread.\" They use these tough beard-like fibers to anchor themselves to rocks and keep themselves in place. So, you see, the mussel's beard is functional rather than merely stylish. Then again, perhaps all beards should be this way.",
        image: "https://acnhapi.com/v1/images/sea/12",
        icon: "https://acnhapi.com/v1/icons/sea/12"
    },
    {
        id: 13,
        name: "oyster",
        northavailability: "September to February",
        southavailability: "March to August",
        time: "All day",
        speed: "Slow",
        shadow: "Small",
        price: 1100,
        catchphrase: "I got an oyster! It's a little shellfish.",
        museumphrase: "Oysters are marvelous mollusks and, in many ways, the social butterflies of the seas. That is, these bivalves tend to live attached to rocks in large groups known as oyster beds. These reef-like structures provide home and habitat for a delightful variety of creatures. Mussels, barnacles, and sea anemones have all been known to set up house. Meanwhile, small fish and crabs hide from predators and even raise their young among the snuggling oysters. With all the hubbub, an oyster bed sounds like the last place one would get some sleep!",
        image: "https://acnhapi.com/v1/images/sea/13",
        icon: "https://acnhapi.com/v1/icons/sea/13"
    },
    {
        id: 14,
        name: "scallop",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        speed: "Slow",
        shadow: "Medium",
        price: 1200,
        catchphrase: "I got a scallop! It otter be savored.",
        museumphrase: "Ah, the scallop! It just goes to show, you can't keep a good bivalve down. While most members of its family are known for staying put, the scallop is a nimble fellow indeed. When a hungry sea star approaches, the scallop can swim away by clap-clap-clapping its shells together! \"How does a scallop know when a predator approaches?\" you ask. Why, it has 200 eyes to see with! It makes one wonder what else the scallop sees with all those eyes... I fear it sees into my very soul!",
        image: "https://acnhapi.com/v1/images/sea/14",
        icon: "https://acnhapi.com/v1/icons/sea/14"
    },
    {
        id: 15,
        name: "whelk",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        speed: "Slow",
        shadow: "Small",
        price: 1000,
        catchphrase: "I got a whelk! Happy snails to ya.",
        museumphrase: "Whelks are sea snails that migrate from deep water to shallow water when the weather changes. Avid carnivores, they feed on worms, crustaceans, and mollusks. In fact, these wily snails have been known to use their own shells to pry open the shells of their victims! They then use a rough tongue-like organ with thousands of tiny teeth to lick their victims' shells clean. Eh... you might want to put that image out of your mind when it's your turn to dine.",
        image: "https://acnhapi.com/v1/images/sea/15",
        icon: "https://acnhapi.com/v1/icons/sea/15"
    },
    {
        id: 16,
        name: "turban shell",
        northavailability: "March to May and September to December",
        southavailability: "Marchto June and September to November",
        time: "All day",
        speed: "Slow",
        shadow: "Small",
        price: 1000,
        catchphrase: "I got a turban shell! It's totally TURB...ular!",
        museumphrase: "The turban shell is a sea snail with a rather nifty trick up its sleeve...er, shell. You see, this snail carries a hard, round, button-like \"operculum\" with it wherever it goes. What is an operculum, you ask? Why, it is a trapdoor of sorts! When danger approaches, the snail slips into its shell and pulls this trapdoor closed over the opening. Thus it is locked safe and sound inside. And bravo, I say! Bravo! When trouble comes knocking, just do what the turban shell￿ does. Shut the door and turn out the lights!",
        image: "https://acnhapi.com/v1/images/sea/16",
        icon: "https://acnhapi.com/v1/icons/sea/16"
    },
    {
        id: 17,
        name: "abalone",
        northavailability: "June to January",
        southavailability: "December to July",
        time: "4pm to 9am",
        speed: "Medium",
        shadow: "Medium",
        price: 2000,
        catchphrase: "I got an abalone! Why do I want a sandwich now?",
        museumphrase: "My feathers, but the abalone is a most deceptive sea snail, wot wot! After seeing its dull brown shell from the outside, one would think it quite plain.But take a gander inside, and you'll see that the abalone's home is a shimmering beauty to behold! The inner layer of the shell is made of nacre, or mother-of-pearl, and, hoo, what a dazzling iridescent hue! Let this be a lesson! You mustn't judge a sea snail by the outside of its shell. Judge it by the inside of its shell instead.",
        image: "https://acnhapi.com/v1/images/sea/17",
        icon: "https://acnhapi.com/v1/icons/sea/17"
    },
    {
        id: 18,
        name: "gigas giant clam",
        northavailability: "May to September",
        southavailability: "November to March",
        time: "All day",
        speed: "Very fast",
        shadow: "Largest",
        price: 15000,
        catchphrase: "I got a gigas giant clam! It's kind of a big deal.",
        museumphrase: "Gigas giant clams live in warm-water coral reefs and are the biggest bivalves in the world. Growing as wide as six feet and weighing up to 600 pounds, these clams can live to be 100 years old. And yes, these mighty creatures look as though they could eat a swimmer whole. But they eat plankton instead and get valuable nutrients from an algae they live in symbiosis with. Indeed, these enormous gents get all the sustenance they need by lying face up with their shells half-open. If such was my life, I'd be happy as a clam too.",
        image: "https://acnhapi.com/v1/images/sea/18",
        icon: "https://acnhapi.com/v1/icons/sea/18"
    },
    {
        id: 19,
        name: "chambered nautilus",
        northavailability: "March to June and September to November",
        southavailability: "March to May and September to December",
        time: "4pm to 9am",
        speed: "Medium",
        shadow: "Medium",
        price: 1800,
        catchphrase: "I got a chambered nautilus! Is it on the naughty list?",
        museumphrase: "The chambered nautilus is perhaps best known for its gorgeous shell. Not only does this shell's interior shine with a pearly luster, it features a near-perfect natural spiral. But those aren't the chambered nautilus's only bragging rights. This cephalopod can have up to 90 tentacles, it's said! These arms come coated with a sticky substance that helps the nautilus capture its prey...Which is far better than using them for overly long hugs, I say.",
        image: "https://acnhapi.com/v1/images/sea/19",
        icon: "https://acnhapi.com/v1/icons/sea/19"
    },
    {
        id: 20,
        name: "octopus",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        speed: "Slow",
        shadow: "Medium",
        price: 1200,
        catchphrase: "I got an octopus! It can give four hugs at once!",
        museumphrase: "With its eight limbs, three hearts, and surprisingly big brain, the octopus is quite the wonder. It is also an escape artist like no other! You see, the octopus has specialized skin cells that can change color and texture with lightening speed. Thus it can look for all the world like a patch of seabed one minute...and a pile of rocks the next! But the deception doesn't stop there, wot wot. When attacked by a predator, the octopus releases a cloud of ink and -POOF- makes its escape. Let's just call the octopus what it is, shall we? The ninja of the deep!",
        image: "https://acnhapi.com/v1/images/sea/20",
        icon: "https://acnhapi.com/v1/icons/sea/20"
    },
    {
        id: 21,
        name: "umbrella octopus",
        northavailability: "March to May and September to November",
        southavailability: "March to May and September to November",
        time: "All day",
        speed: "Fast",
        shadow: "Small",
        price: 6000,
        catchphrase: "I got an umbrella octopus! Too bad I'm already soaked.",
        museumphrase: "My feathers, could there be a more adorable sea creature than the umbrella octopus? I daresay not! These deep-sea octopuses are on the smallish side and use the cutest ear-like fins to flutter about. Meanwhile, it's the web stretched between their tentacles that gives them their name. Hoo, it's true! With arms stretched wide, they look for all the world like an umbrella! Though surely the last thing the umbrella octopus wants...is to stay dry.",
        image: "https://acnhapi.com/v1/images/sea/21",
        icon: "https://acnhapi.com/v1/icons/sea/21"
    },
    {
        id: 22,
        name: "vampire squid",
        northavailability: "May to August",
        southavailability: "November to February",
        time: "4pm to 9am",
        speed: "Very fast",
        shadow: "Medium",
        price: 10000,
        catchphrase: "I got a vampire squid! A lot was at stake.",
        museumphrase: "Beware the vampire squid, I say! This eight-armed deep-sea monster is out to drink your blood! Hoo hoo, ha ha! I only jest! Ahem! The Vampire Squid does, in fact, live deep in the ocean where almost no light pervades. But while it looks like it could nibble on your neck...it nibbles on the bits of dead plankton and algae instead. By all accounts, the vampire squid is a a gentle sort who squirts bioluminecesant goo at foes. Sp, how did it get the eerie official name Vampyroteuthis inernalis? That means vampire squid from the heck, you see. The problem is that the squid's cloak. Its arms are webbed with velvet-red skin and lined with toothy spikes. Plainly put, this genial squid looks for all the world like a vampire who went for a swim.",
        image: "https://acnhapi.com/v1/images/sea/22",
        icon: "https://acnhapi.com/v1/icons/sea/22"
    },
    {
        id: 23,
        name: "firefly squid",
        northavailability: "March to June",
        southavailability: "September to December",
        time: "9pm to 4am",
        speed: "Slow",
        shadow: "Smallest",
        price: 1400,
        catchphrase: "I got a firefly squid! More like a glowswim squid.",
        museumphrase: "The firefly squid is a wee migratory squid that barely reaches three inches in length. And though they usually live in deep water, they do venture to the coast to spawn. Like their firefly namesakes, these sparkling squid emit a blue bioluminescent glow. This glow may be used to threaten enemies, communicate with friends, or, perhaps, to lure food in. Truth be told, we do not know for sure why the firefly squid glows. We remain in the dark, as they say.",
        image: "https://acnhapi.com/v1/images/sea/23",
        icon: "https://acnhapi.com/v1/icons/sea/23"
    },
    {
        id: 24,
        name: "gazami crab",
        northavailability: "June to November",
        southavailability: "December to May",
        time: "All day",
        speed: "Medium",
        shadow: "Medium",
        price: 2200,
        catchphrase: "I got a gazami crab! What a gripping find!",
        museumphrase: "The gazami crab may be better known by its more descriptive name… the Japanese blue crab. It gets its name from the blue tint sometimes found in its shell and legs. Its paddle-like rear legs are what help it to swim freely and quickly through the water. Of course, this gazami crab couldn't swim enough to get away from you!",
        image: "https://acnhapi.com/v1/images/sea/24",
        icon: "https://acnhapi.com/v1/icons/sea/24"
    },
    {
        id: 25,
        name: "dungeness crab",
        northavailability: "November to May",
        southavailability: "May to November",
        time: "All day",
        speed: "Medium",
        shadow: "Medium",
        price: 1900,
        catchphrase: "I got a Dungeness crab! Dun dun duuuun...geness.",
        museumphrase: "The Dungeness crab wears a pretty fan-shaped shell that's often done up in purple hues. But eye-catching colors aside, this fellow can be surprisingly hard to spot! That's because the Dungeness crab is something of an expert hider. When scared, it plays a nifty trick! That is, it buries itself beneath the sand with impressive speed. Now you see me, now you don't, it says as it vanishes before your very eyes!",
        image: "https://acnhapi.com/v1/images/sea/25",
        icon: "https://acnhapi.com/v1/icons/sea/25"
    },
    {
        id: 26,
        name: "snow crab",
        northavailability: "November to April",
        southavailability: "May to October",
        time: "All day",
        speed: "Fast",
        shadow: "Large",
        price: 6000,
        catchphrase: "I got a snow crab! It's giving me the cold shoulder.",
        museumphrase: "The snow crab truly lives up to its name, wot wot. They are most often found in cold northern seas. Some have even been discovered living in the Arctic Ocean! Indeed, snow crab prefer to live in deep water that never gets more than three degrees above freezing. Hooooo. Just thinking about their icy environs is giving me the chills!",
        image: "https://acnhapi.com/v1/images/sea/26",
        icon: "https://acnhapi.com/v1/icons/sea/26"
    },
    {
        id: 27,
        name: "red king crab",
        northavailability: "November to March",
        southavailability: "May to September",
        time: "All day",
        speed: "Very fast",
        shadow: "Large",
        price: 8000,
        catchphrase: "I caught a red king crab! It's royally flushed.",
        museumphrase: "The red king crab is a mighty crustacean to be sure. Though it must be said that there is some debate about its royal lineage. King crabs, unlike other crabs, are thought to be descended from hermit crabs, you see. And have you noticed... GASP! They have but eight legs, though conventional crabs have 10! It matters not, I say. For the red king crab is as regal as can be. Weighing up to 20 pounds with a leg span reaching five feet... I bow to this crab's nobility.",
        image: "https://acnhapi.com/v1/images/sea/27",
        icon: "https://acnhapi.com/v1/icons/sea/27"
    },
    {
        id: 28,
        name: "acorn barnacle",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "All day",
        speed: "Stationary",
        shadow: "Smallest",
        price: 600,
        catchphrase: "I got an acorn barnacle! Will it grow into an oak barnacle?",
        museumphrase: "Do not mistake the acorn barnacle for a relative of the calm. Tut-tut, mollusks they are not. Barnacles are cousins to crabs and lobsters, you see. Though the family resemblance is hard to spot. Acorn barnacles may also seem to live a stationary life, what with being attached to rocks and such. But truth be told, baby barnacles are avid travelers, drifting shell-less about the sea before settling down. Once they find a good rock to affix themselves to, they float free no more. Which begs the question... Do adult acorn barnacles ever look out across the open sea...and long for youthful adventure once more?",
        image: "https://acnhapi.com/v1/images/sea/28",
        icon: "https://acnhapi.com/v1/icons/sea/28"
    },
    {
        id: 29,
        name: "spider crab",
        northavailability: "March to April",
        southavailability: "September to October",
        time: "All day",
        speed: "Very fast",
        shadow: "Largest",
        price: 12000,
        catchphrase: "I got a spider crab! Water bugs can rest easy.",
        museumphrase: "Hoooot hooot, I do so hope to not hyperventilate as I regale you with the spider crab's qualities. But I would be remiss if I did not point out that this, the largest crab on earth... looks like a GIANT SPIDER! Arachnophobia aside... this crab is a magnificent creature to be sure. Though they can grow up to 12 feet from claw to claw and weigh up to 40 pounds, they're said to be docile. In fact, these gentle giants love to hide, attaching seaweed and sponges to their shell as camouflage. My feathers, if only I could unsee the SPIDER in the spider crab... I'm sure I'd find it charming as can be.",
        image: "https://acnhapi.com/v1/images/sea/29",
        icon: "https://acnhapi.com/v1/icons/sea/29"
    },
    {
        id: 30,
        name: "tiger prawn",
        northavailability: "June to September",
        southavailability: "December to March",
        time: "4pm to 9am",
        speed: "Medium",
        shadow: "Small",
        price: 3000,
        catchphrase: "I got a tiger prawn! I ain't lion!",
        museumphrase: "The tiger prawn is a hearty crustacean found in many places around the world. Named for the stripes on its exoskeleton, it molts out of this shell as it grows in size. If only I could acquire a larger home with such ease! But do you know what I find even more fascinating? The tiger prawn's legs! It has five pairs of swimming legs, five pairs of walking legs, and three pairs of limbs it eats with! How, might I ask, does it not trip over its own 26 feet?",
        image: "https://acnhapi.com/v1/images/sea/30",
        icon: "https://acnhapi.com/v1/icons/sea/30"
    },
    {
        id: 31,
        name: "sweet shrimp",
        northavailability: "September to February",
        southavailability: "March to August",
        time: "4pm to 9am",
        speed: "Slow",
        shadow: "Small",
        price: 1400,
        catchphrase: "I got a sweet shrimp! It's being very considerate.",
        museumphrase: "The sweet shrimp spends the first few years of its life as a male. It then transitions into a female as it ages. Interestingly, it is hardly alone in this type of development cycle. Indeed, a great variety of marine creatures can change their biological sex as they age. Clown fish, some sea star, and sea bass are among them. Hoo hoo, the ocean is full of a great many wonders. Huzzah to that, I say!",
        image: "https://acnhapi.com/v1/images/sea/31",
        icon: "https://acnhapi.com/v1/icons/sea/31"
    },
    {
        id: 32,
        name: "mantis shrimp",
        northavailability: "January to December",
        southavailability: "January to December",
        time: "4pm to 9am",
        speed: "Medium",
        shadow: "Small",
        price: 2500,
        catchphrase: "I got a mantis shrimp! Shrimply amazing!",
        museumphrase: "Think carefully before you mock the mantis shrimp for its diminutive size. I warn you, it's itching for a fight! A pugilist through and through, this brightly hued fellow packs a punch unparalleled on land or sea. Not only are its forelimbs shaped like clubs and scythes, its arms are naturally spring-loaded too! Thus the mantis shrimp's high-speed blows crack open crabs and oyster shells with ease. And should you grab it with your hands, you might discover why it's called the thumb splitter too!",
        image: "https://acnhapi.com/v1/images/sea/32",
        icon: "https://acnhapi.com/v1/icons/sea/32"
    },
    {
        id: 33,
        name: "spiny lobster",
        northavailability: "October to December",
        southavailability: "April to June",
        time: "9pm to 4am",
        speed: "Fast",
        shadow: "Large",
        price: 5000,
        catchphrase: "I got a spiny lobster! It's got a lot of backbone!",
        museumphrase: "It is the spiny lobster's lengthy antennae that help set it apart from other lobsters. Those two antennae can grow twice as long as the lobster's own body! And what a clever crustacean it is, having found a way to use those antennae as a means of defense. When the spiny lobster senses danger, it rubs its antennae across its exoskeleton. The horrid screeching sound frightens predators away! If someone scratched nails across a chalkboard in your direction, I daresay you'd run too!",
        image: "https://acnhapi.com/v1/images/sea/33",
        icon: "https://acnhapi.com/v1/icons/sea/33"
    },
    {
        id: 34,
        name: "lobster",
        northavailability: "December to January and April to June",
        southavailability: "June to July and October to December",
        time: "All day",
        speed: "Fast",
        shadow: "Large",
        price: 4500,
        catchphrase: "I got a lobster! Lobjective complete.",
        museumphrase: "The lobster is rather famous for its two large claws. But did you know that, in fact, it has six claws total? Of course, the four tiny claws aren't as threatening as its large \"crusher claw\" is. That pincer can put a hundred pounds of pressure on in a pinch! Just a little something to bear in mind when a lobster tries to shake your hand.",
        image: "https://acnhapi.com/v1/images/sea/34",
        icon: "https://acnhapi.com/v1/icons/sea/34"
    },
    {
        id: 35,
        name: "giant isopod",
        northavailability: "July to October",
        southavailability: "January to April",
        time: "9am to 4pm and 9pm to 4am",
        speed: "Very fast",
        shadow: "Medium",
        price: 12000,
        catchphrase: "GAAAAH! I got a giant isopod! It's the crustodian of the sea.",
        museumphrase: "Growing up to nearly 20 inches, the sea-dwelling giant isopod is the world's largest cousin of the pill bug. Twenty inches?! Twenty times as revolting, I say! Making matters worse for those of us who find the pill bug repulsive rather than cute... The giant isopod can swim shockingly fast and is known for its voracious appetite. In fact, it's most happy when dining on the carcasses of animals that have sunk to the bottom of the sea! This behavior has earned it a nickname... 'the vacuum cleaner of the deep.' Why must nature play such awful pranks on me?",
        image: "https://acnhapi.com/v1/images/sea/35",
        icon: "https://acnhapi.com/v1/icons/sea/35"
    },
    {
        id: 36,
        name: "horseshoe crab",
        northavailability: "July to September",
        southavailability: "January to March",
        time: "9pm to 4am",
        speed: "Medium",
        shadow: "Medium",
        price: 2500,
        catchphrase: "I got a horseshoe crab! I hope it's lucky!",
        museumphrase: "Some might say it's good luck to catch a horseshoe crab. But I am NOT among them, eh wot! Though called a \"crab,\" this beast is an arthropod and thus more akin to spiders and scorpions! Its long tail resembles a scorpion stinger, in fact! Though it's quite harmless, they say. A living fossil, the horseshoe crab has been around since before the dinosaurs. With that tank-like shell, I suppose it WOULD be the one to survive. But here's what truly rattles me to my beak... During breeding season, horseshoe crabs crawl up on the beach and make nests together in the hundreds. HUNDREDS OF HORSESHOE CRABS! And with that I can say no more.",
        image: "https://acnhapi.com/v1/images/sea/36",
        icon: "https://acnhapi.com/v1/icons/sea/36"
    },
    {
        id: 37,
        name: "sea pineapple",
        northavailability: "April to August",
        southavailability: "October to February",
        time: "All day",
        speed: "Slow",
        shadow: "Small",
        price: 1500,
        catchphrase: "I got a sea pineapple! Your move, sea pizzas.",
        museumphrase: "Try not to gawk as you look upon the sea pineapple. Its peculiar look is simply one of nature's many jokes. Though it may look like a half-rotten hunk of fruit, the sea pineapple is no plant, shellfish, or even sea slug. It's a tunicate, wot wot...a fancy name for a shallow-water filter feeder with a taste for plankton. It should be noted that the sea pineapple looks like a tadpole when it's young and can still swim about. Alas, its youthful cuteness wears off once it attaches itself for good to a rock. Ah, but let's put insults aside! Sea pineapples are full of water, you sea. And I fear we're asking for a squirt in the eye!",
        image: "https://acnhapi.com/v1/images/sea/37",
        icon: "https://acnhapi.com/v1/icons/sea/37"
    },
    {
        id: 38,
        name: "spotted garden eel",
        northavailability: "May to October",
        southavailability: "November to April",
        time: "4am to 9pm",
        speed: "Stationary",
        shadow: "Large",
        price: 160,
        catchphrase: "I got a spotted garden eel! Was it un-spotted before I saw it?",
        museumphrase: "The spotted garden eel is a small eel-shaped fish that loves to burrow in the sandy ocean floor. These silly things are known for popping their heads out of the sand to nibble on plankton drifting by. Some say this makes them look like plants sprouting in a garden...hence the name spotted garden eel. But I think they look more like prairie dogs peeking out of desert hidey-holes. Prairie eels has a lovely ring, don't you think?",
        image: "https://acnhapi.com/v1/images/sea/38",
        icon: "https://acnhapi.com/v1/icons/sea/38"
    },
    {
        id: 39,
        name: "flatworm",
        northavailability: "August to September",
        southavailability: "February to March",
        time: "4pm to 9am",
        speed: "Very Slow",
        shadow: "Smallest",
        price: 700,
        catchphrase: "I got a flatworm! Guess it forgot its spareworm.",
        museumphrase: "Flatworms are flat creatures, and while some types look like sea slugs, they have little else in common. Some types are venomous and produce a poison similar to the kind blowfish are famous for. Flatworms are hermaphrodites and mate by fighting to determine the loser, who then bears the eggs.",
        image: "https://acnhapi.com/v1/images/sea/39",
        icon: "https://acnhapi.com/v1/icons/sea/39"
    },
    {
        id: 40,
        name: "Venus' flower basket",
        northavailability: "October to February",
        southavailability: "April to August",
        time: "All day",
        speed: "Fast",
        shadow: "Medium",
        price: 5000,
        catchphrase: "I got a Venus' flower basket! Why was she picking flowers here?",
        museumphrase: "The Venus' flower basket looks like an otherworldly creature one would find on an alien planet. But it is instead a remarkable sea sponge found in the deepest parts of the ocean. Its body is composed of silica and looks like a sculpture or, perhaps, a vase made of glassy mesh. I daresay Venus' flower basket is one of nature's most impressive works of art.",
        image: "https://acnhapi.com/v1/images/sea/40",
        icon: "https://acnhapi.com/v1/icons/sea/40"
    }
];